# Posts 21-40 of the 60-post batch (p111-p130).

POSTS_B = [
    # 21 — p111 tips: smelly hot water causes
    dict(
        pillar="tips",
        topic="Why your hot water smells odd — and what it means",
        slug="plumbing", suffix="smelly-hot-water",
        hint="work:tank_service", itype="work", banner="upper",
        caption="Hot water smells odd? Here's why 👃",
        cta="QUOTE", extra_cta=None,
        fb="👃 Hot water smelling of rotten eggs — but ONLY from the hot taps?\n\nThat's not a gas problem (gas smell is constant and needs 0800 111 999). A smell only in heated water usually points to the hot water cylinder:\n\n🛢️ Stored water sitting too cool — bacteria love a lukewarm tank\n🛢️ A worn sacrificial anode reacting with the water\n🛢️ A cylinder overdue a clean-out\n\nThe fix is usually simple: cylinder up to 60°C, a flush-through, and a check of the immersion thermostat. Cheap, quick, and your morning shower stops smelling like a school science lab.",
        ig="Rotten-egg smell — but only from the HOT taps? 👃\n\nThat's not gas (a gas smell is constant — that's an 0800 111 999 call). A smell only in heated water usually means the hot water cylinder:\n\n🛢️ Water stored too cool — bacteria love a lukewarm tank\n🛢️ A worn anode reacting with the water\n🛢️ A cylinder overdue a clean-out\n\nUsually a simple fix: cylinder up to 60°C, flush through, check the immersion stat. Your morning shower stops smelling like a science lab.",
        tw="Rotten-egg smell from the HOT taps only? That's your cylinder, not gas. 👃\n\nUsual causes: water stored too cool, a worn anode, or a tank overdue a flush. Simple fix — 60°C, flush, done.",
        gb="If your hot water has developed a rotten-egg smell — but only from the hot taps — the cause is usually the hot water cylinder rather than anything sinister. (A gas smell is constant and should always go straight to the National Gas Emergency line on 0800 111 999.) Water stored below 60°C gives bacteria a comfortable environment, a worn sacrificial anode can react with the water, and an older cylinder may simply be due a clean-out. The remedy is normally straightforward: bring the cylinder up to temperature, flush the stored water through, and verify the immersion thermostat is working correctly. Cylinder and hot water work across Southampton.",
        tags=["#HotWater", "#PlumbingTips", "#WaterCylinder", "#HomeTips"],
    ),
    # 22 — p112 work: install day walkthrough
    dict(
        pillar="work",
        topic="Job story — a boiler install day, start to finish",
        slug="boiler-install", suffix="install-day",
        hint="work:install", itype="work", banner="lower",
        caption="Install day, start to finish 🔧",
        cta="QUOTE", extra_cta=None,
        fb="🔧 What a boiler install day actually looks like:\n\n8am — dust sheets down, system drained\n9.30 — old boiler off the wall\n11 — new boiler mounted, pipework adapted, magnetic filter in\n1pm — system flushed, inhibitor added\n2.30 — commissioning: gas rate, flue analysis, every setting dialled in for the house\n4pm — controls talk-through, paperwork done, warranty registered, kettle's yours again\n\nOne day. No drama. No 'we'll be back Thursday to finish off'.",
        ig="Install day, hour by hour 🔧\n\n8am — dust sheets down, system drained\n9.30 — old boiler off the wall\n11am — new one mounted, pipework adapted, filter in\n1pm — system flushed, inhibitor added\n2.30 — commissioning: gas rate, flue analysis, settings dialled in\n4pm — controls talk-through, warranty registered, kettle's yours again\n\nOne day. No drama. No 'we'll be back Thursday to finish off'.",
        tw="A boiler install day: 8am dust sheets, 9.30 old one off the wall, 1pm flush + inhibitor, 2.30 commissioning, 4pm handover with the warranty registered. One day, no drama. 🔧",
        gb="Customers often ask what a boiler installation actually involves, so here's a typical day. By 8am the dust sheets are down and the system is draining. The old boiler is off the wall by mid-morning; the new one is mounted, the pipework adapted and a magnetic filter fitted before lunch. The system is then flushed and dosed with inhibitor, and the afternoon goes on commissioning — gas rate checks, flue gas analysis, and settings tuned to the house rather than left on factory defaults. By 4pm you get a proper walk-through of the controls, the paperwork, and a registered warranty. One day, no loose ends. Boiler installations across Southampton.",
        tags=["#BoilerInstall", "#NewBoiler", "#InstallDay", "#HeatingUpgrade"],
    ),
    # 23 — p113 trust: what Gas Safe actually means for you
    dict(
        pillar="trust",
        topic="What 'Gas Safe registered' actually means for you",
        slug="gas-safety", suffix="gas-safe-meaning",
        hint="asset:gas", itype="asset", banner="upper",
        caption="What 'Gas Safe' actually means ✅",
        cta="SERVICE", extra_cta=None,
        fb="✅ 'Gas Safe registered' — you see it everywhere. Here's what it actually means for YOU:\n\n🪪 It's the official legal register. Only registered engineers are allowed to touch gas appliances in the UK. Not 'recommended' — required by law.\n🪪 Every registered engineer carries a photo ID card listing exactly what work they're qualified for — boilers, hobs, fires.\n🪪 You can check any engineer on the Gas Safe register before they set foot in your house.\n\nAsk to see the card. Good engineers expect it — I'd rather you check than wonder.",
        ig="What does 'Gas Safe registered' actually mean for you? ✅\n\n🪪 It's the legal register — only registered engineers may work on gas in the UK. Not 'recommended'. Required by law.\n🪪 Every engineer carries photo ID listing exactly what they're qualified to work on\n🪪 You can look any engineer up on the register before they touch your boiler\n\nAsk to see the card. Good engineers expect it — I'd much rather you check than wonder.",
        tw="'Gas Safe registered' isn't a badge — it's the legal register. Only registered engineers may work on gas in the UK. ✅\n\nAsk to see the ID card. Good engineers expect it.",
        gb="The phrase 'Gas Safe registered' appears on every heating engineer's van, but it's worth knowing what it actually guarantees you as a customer. Gas Safe is the official register of engineers legally permitted to work on gas appliances in the UK — it isn't a trade body membership or a marketing badge, it's a legal requirement. Every registered engineer carries a photo ID card listing the specific categories of work they're qualified to carry out, and you can verify any engineer on the register before they start. You should always feel comfortable asking to see the card; a professional will expect it. Gas safety checks and gas work across Southampton.",
        tags=["#GasSafe", "#GasSafety", "#HomeSafety", "#TrustedTrader"],
    ),
    # 24 — p114 local mascot: Itchen Bridge
    dict(
        pillar="local",
        topic="Where's Wes today? — Itchen Bridge",
        slug="plumbing", suffix="wes-itchen-bridge",
        hint="asset:logo_mascot", itype="asset", banner="lower",
        caption="Where's Wes today? 📍 Itchen Bridge",
        cta=None, extra_cta="Guessed it already? Tell me where he should turn up next 👇",
        fb="📍 Where's Wes today? Stop two on the tour: the Itchen Bridge!\n\nThe only crossing in town that charges you to get over it. 😄 Little Wes paid his toll like everyone else — no special treatment for mascots.\n\nIt's also the route I take more than any other: Woolston, Sholing and Netley one side, the city the other, and jobs on both.\n\nWherever you are on either bank, you're on the round.",
        ig="Where's Wes today? Stop two: the Itchen Bridge 📍\n\nThe only crossing in town that charges you to get over it 😄 Little Wes paid his toll like everyone else. No special treatment for mascots.\n\nIt's also the route I drive more than any other — Woolston, Sholing and Netley on one side, the city on the other, jobs on both.\n\nWherever you are on either bank, you're on the round.\n\nWhere should he pop up next? 👇",
        tw="Where's Wes today? 📍 The Itchen Bridge — the only crossing in town that charges a toll. Little Wes paid like everyone else. 😄\n\nBoth banks covered, every week.",
        gb="Stop two on the Better Call Wes mascot tour of Southampton: the Itchen Bridge. It's a fitting choice — this is the route I drive more than any other, with Woolston, Sholing and Netley on one side, the city centre on the other, and customers on both banks. The real work behind the fun: plumbing repairs, boiler servicing and repairs, and heating work across every Southampton postcode, from one local Gas Safe registered engineer with clear up-front pricing. Follow the page to see which landmark the little fella visits next — suggestions are very welcome.",
        tags=["#Southampton", "#ItchenBridge", "#Woolston", "#SouthamptonLife", "#WheresWes"],
        prompt="TASK: Place the cartoon mascot character from the source image into a new scene.\n\nSOURCE: The input image is the Better Call Wes logo featuring a cartoon mascot of a Black African plumber in a navy polo holding a wrench and phone. Preserve the mascot's exact appearance, style, colours, and proportions.\n\nSCENE: A photorealistic view of the Itchen Bridge in Southampton — the long concrete road bridge arching high over the River Itchen, water glinting below, the Woolston shoreline and moored boats in the background under a bright sky — with the cartoon mascot standing playfully in the foreground giving a thumbs up — deliberate cartoon-on-photo contrast, like a mascot sticker on a postcard.\n\nCHANGE: Add ONE caption banner in the lower third.\n- Banner style: solid rectangle, brand navy #0A2540, 88% opacity, full-width, 14% of image height, clean edges\n- Small orange #FF6B00 accent bar, 4px, along the top edge of the banner\n- Headline (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Where's Wes today? 📍 Itchen Bridge\"\n- Typography: bold sans-serif, white, centred, generous kerning, optically sized for social-feed legibility\n\nCONSTRAINTS: Render the headline verbatim. No other text anywhere in the image. Keep the mascot's identity, colours and proportions exactly as in the source. No watermark. No extra logos.\n\nUSE CASE: Instagram social post, square 1:1, 1080x1080.",
    ),
    # 25 — p115 cost_reveal: TRV upgrade costs/savings
    dict(
        pillar="cost_reveal",
        topic="TRVs — the small valves with real savings",
        slug="radiators", suffix="trv-upgrade",
        hint="asset:radiator", itype="asset", banner="lower",
        caption="Little valves, real savings 🌡️",
        cta="QUOTE", extra_cta=None,
        fb="🌡️ The cheapest heating zoning system ever invented is already half-fitted in most houses: the TRV.\n\nThose numbered valves on your radiators let every room run its own temperature. Spare room you use twice a month? Setting 1–2. Living room? 3–4. That's heat going only where you actually live.\n\n💷 The valves themselves are modest money, fitting is quick, and the saving compounds every single heating day.\n\nGot radiators with no TRVs at all — or ancient ones that don't really respond? That's an upgrade that quietly pays you back.",
        ig="The cheapest zoning system ever invented 🌡️\n\nIt's already half-fitted in your house: the humble TRV.\n\nThose numbered radiator valves let every room run its own temperature:\n\n🛏️ Spare room you barely use? 1–2\n🛋️ Living room? 3–4\n\nHeat goes only where you actually live — and the saving repeats every heating day of the year.\n\nRads with no TRVs, or ancient stiff ones that don't respond? That upgrade quietly pays you back.",
        tw="TRVs = the cheapest heating zoning ever invented. 🌡️\n\nSpare room on 1, lounge on 3, heat only where you live. Modest cost, quick fit, and the saving repeats every heating day.",
        gb="Thermostatic radiator valves are easy to overlook, but they're the cheapest room-by-room heating control available. Each numbered valve regulates its own radiator: a spare room that's rarely used can sit at setting 1–2 while the living room runs at 3–4, so you stop paying to heat rooms nobody is in. The valves are modest in cost, fitting is quick, and the saving repeats every day the heating runs. If some of your radiators have no TRVs at all — or older valves that have stiffened and no longer respond — upgrading them is one of the better-value improvements you can make to a heating system. Radiator and valve work across Southampton.",
        tags=["#TRV", "#RadiatorTips", "#EnergySaving", "#CentralHeating"],
    ),
    # 26 — p116 personal: what 10 years in Southampton taught me
    dict(
        pillar="personal",
        topic="What ten years working Southampton's homes taught me",
        slug="boiler-repair", suffix="ten-years",
        hint="brand:wes_portrait", itype="brand", banner="lower",
        caption="10 years working Southampton's homes 🏠",
        cta=None, extra_cta="Not needed me yet? Lucky you — save the number for the day you do.",
        fb="🏠 Ten years working on Southampton's homes teaches you things no college course covers:\n\n💧 Our hard water is brutal on heat exchangers — treat for it or pay for it\n🧱 1930s semis hide pipework in places that defy all logic\n💷 The cheapest quote is usually the dearest by year three\n☕ And a cup of tea offered at the door is this city's love language\n\nEvery winter I learn something new. Usually from a boiler that's found an original way to sulk.",
        ig="Ten years in Southampton's homes. Some lessons: 🏠\n\n💧 Our hard water is brutal on heat exchangers — treat for it or pay for it\n🧱 1930s semis hide pipes in places that defy logic\n💷 The cheapest quote is usually the dearest by year three\n☕ And a cuppa offered at the door is this city's love language\n\nEvery winter a boiler still finds an original new way to sulk. Keeps me humble.",
        tw="10 years in Southampton's homes taught me: hard water is brutal on boilers, 1930s semis hide pipes illogically, and the cheapest quote is the dearest by year three. 🏠",
        gb="Ten years of working in Southampton's homes teaches lessons no qualification covers. The local hard water is genuinely tough on boiler heat exchangers — systems that get water treatment last visibly longer than those that don't. The city's 1930s semis hide pipework in places that defy logic, so experience with the housing stock saves customers real time. And the pattern I've seen most often: the cheapest quote tends to become the most expensive choice by year three, once corners cut start surfacing. I'm grateful to every household that's had me through the door — and to the boilers that still find new ways to keep me learning.",
        tags=["#Southampton", "#LocalBusiness", "#TenYears", "#HeatingEngineerLife"],
    ),
    # 27 — p117 local: Romsey
    dict(
        pillar="local",
        topic="Area coverage — Romsey",
        slug="boiler-repair", suffix="romsey",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering Romsey 📍",
        cta="QUOTE", extra_cta=None,
        fb="📍 Romsey — the SO51 end of the round.\n\nMarket town charm comes with market town heating: period properties, solid walls, systems extended and patched over decades. Lovely houses. Interesting pipework.\n\n🔧 Boiler repairs with a £100 diagnostic\n🔥 Servicing for systems old and new\n🏠 Honest advice on whether that veteran boiler has another winter in it\n\nFrom the Abbey end to the newer estates, you're covered — without the 'out of area' surcharge nonsense.",
        ig="Romsey, you're on the round 📍\n\nMarket town charm = market town heating. Period properties, solid walls, systems extended and patched over decades. Lovely houses. *Interesting* pipework.\n\n🔧 Boiler repairs (£100 diagnostic)\n🔥 Servicing for systems old and new\n🏠 Straight answers on whether that veteran boiler has another winter in it\n\nAbbey end to the new estates — covered, no 'out of area' surcharge nonsense.",
        tw="Romsey 📍 SO51 is on the round — boiler repairs, servicing, and straight answers about veteran heating systems in period homes. No out-of-area surcharges.",
        gb="Romsey marks the SO51 end of my regular round, and it's an area I know well. Market town housing brings its own heating challenges: period properties with solid walls, systems that have been extended and patched across decades, and veteran boilers soldiering on past their best. I provide boiler repairs with a £100 diagnostic, annual servicing for systems old and new, and honest advice on whether an ageing boiler genuinely has another winter left in it — repair and replacement both get a fair hearing, with the maths explained. From the Abbey end of town to the newer estates, Romsey is covered without out-of-area surcharges.",
        tags=["#Romsey", "#SO51", "#BoilerRepair", "#Hampshire"],
    ),
    # 28 — p118 tips: noisy pipes at night
    dict(
        pillar="tips",
        topic="Pipes banging and ticking at night — causes and fixes",
        slug="central-heating", suffix="noisy-pipes",
        hint="asset:pipe", itype="asset", banner="upper",
        caption="Pipes banging at night? 🔊",
        cta=None, extra_cta="Save this for the next 2am clank.",
        fb="🔊 Pipes that tick, creak or BANG at night — here's what your house is trying to say:\n\n🔥 Ticking as heating warms up or cools down = pipes expanding against joists. Annoying, rarely serious.\n💥 A single thud when a tap or washing machine shuts off = water hammer. A valve slamming shut.\n💨 Tapping or gurgling from radiators = air in the system. Bleed them.\n🫖 Rumbling from the boiler itself = kettling — scale or sludge. That one deserves attention.\n\nMost night noises are harmless. The boiler rumble isn't. Know the difference and you'll sleep better — literally.",
        ig="What your pipes are saying at 2am 🔊\n\n🔥 Ticking as heating warms/cools = pipes expanding against joists. Annoying, rarely serious\n💥 One thud when a tap or machine shuts off = water hammer — a valve slamming\n💨 Tapping/gurgling from rads = air in the system. Bleed them\n🫖 Rumbling from the boiler = kettling — scale or sludge. That one matters\n\nMost night noises are harmless. The boiler rumble isn't. Know the difference, sleep better.",
        tw="Pipes at 2am, translated 🔊\n\nTicking = expansion, harmless\nThud after a tap shuts = water hammer\nGurgling rads = air, bleed them\nRumbling BOILER = kettling — that one needs a look",
        gb="Night-time pipe noises have distinct causes, and telling them apart saves worry. Ticking or creaking as the heating warms up and cools down is thermal expansion — pipes moving slightly against joists, irritating but rarely serious. A single thud when a tap or washing machine shuts off is water hammer, caused by a valve closing abruptly, and can be cured with an arrestor or pressure adjustment. Tapping or gurgling from radiators means trapped air that bleeding will release. The noise that genuinely warrants attention is a rumbling from the boiler itself — kettling, the sound of water boiling against scale or sludge, which shortens the boiler's life. Heating diagnostics across Southampton.",
        tags=["#PlumbingTips", "#NoisyPipes", "#CentralHeating", "#HomeTips"],
    ),
    # 29 — p119 work: diagnostic story (multimeter find)
    dict(
        pillar="work",
        topic="Job story — the intermittent fault the multimeter found",
        slug="boiler-repair", suffix="multimeter-find",
        hint="work:boiler_repair", itype="work", banner="lower",
        caption="The multimeter never lies 🔍",
        cta="QUOTE", extra_cta=None,
        fb="🔍 A boiler in Shirley kept cutting out. No fault code. No pattern. The kind of problem that gets expensive when people start guessing.\n\nSo: no guessing. Multimeter on the thermistor while the boiler warmed up — and there it was. The resistance readings drifted out of spec as it got hot, telling the board the water was boiling when it wasn't. Boiler shuts down, cools off, readings recover, fires up again. Repeat forever.\n\nOne sensor swapped. Behaving ever since.\n\nGuesswork replaces parts. Measurement replaces the RIGHT part.",
        ig="No fault code. No pattern. Just a boiler that kept dying. 🔍\n\nA Shirley combi kept cutting out randomly — the kind of fault that gets expensive when people start guessing at parts.\n\nSo, no guessing. Multimeter on the thermistor while it warmed up… and there it was. Readings drifting out of spec as it got hot — telling the board the water was boiling when it wasn't. Shut down, cool off, recover, repeat.\n\nOne sensor swapped. Behaving ever since.\n\nGuesswork replaces parts. Measurement replaces the RIGHT part.",
        tw="Boiler in Shirley cutting out — no code, no pattern. 🔍\n\nMultimeter on the thermistor: readings drifting, faking a boil. One sensor swapped — sorted.\n\nMeasurement beats guesswork.",
        gb="A recent diagnostic job in Shirley: a combi boiler kept cutting out with no fault code and no obvious pattern — exactly the kind of intermittent problem that becomes expensive when engineers start swapping parts on guesswork. The methodical route: multimeter on the thermistor while the boiler warmed through. The resistance readings drifted out of specification as temperatures rose, effectively telling the control board the water was boiling when it wasn't, so the boiler shut itself down, cooled, recovered and repeated the cycle. One sensor replaced, and it has behaved since. Proper diagnosis costs a little patience and saves a lot of parts. Boiler repairs across Southampton with a £100 diagnostic.",
        tags=["#BoilerRepair", "#Shirley", "#Diagnostics", "#FixedRight"],
    ),
    # 30 — p120 cost_reveal: what landlords lose to heating failures
    dict(
        pillar="cost_reveal",
        topic="What a heating failure really costs a landlord",
        slug="cp12", suffix="landlord-voids",
        hint="asset:gas", itype="asset", banner="upper",
        caption="What a cold rental really costs 💷",
        cta="QUOTE", extra_cta=None,
        fb="💷 Landlords — the spreadsheet never shows the real cost of a heating failure:\n\n🏠 A dead boiler between tenancies = move-in dates pushed back, and every void week is a week's rent gone\n📞 Mid-tenancy failures = emergency rates, unhappy tenants, and goodwill you can't buy back\n📋 An expired CP12 = you legally can't start the tenancy at all\n\nNow the boring alternative: serviced system, CP12 renewed ahead of time, small faults caught at the annual visit. A year of planned maintenance costs less than one void week.\n\nBoring wins. Every time.",
        ig="Landlords: the real cost of a cold rental 💷\n\n🏠 Dead boiler between tenancies = pushed-back move-ins. Every void week is a week's rent, gone\n📞 Mid-tenancy failure = emergency rates + tenant goodwill you can't buy back\n📋 Expired CP12 = legally, the tenancy can't even start\n\nThe boring alternative: serviced system, CP12 renewed early, faults caught at the annual visit.\n\nA year of planned maintenance costs less than ONE void week. Boring wins.",
        tw="Landlords: one void week from a dead boiler costs more than a year of planned maintenance. 💷\n\nServiced system + CP12 renewed ahead of time = boring. Boring wins.",
        gb="For landlords, heating failures cost far more than the repair invoice. A dead boiler between tenancies pushes move-in dates back, and every void week is a full week's rent lost. A mid-tenancy breakdown means emergency call-out rates and tenant goodwill that's hard to win back. And an expired gas safety certificate stops a new tenancy starting at all — it's a legal requirement, not paperwork. The unglamorous alternative works out far cheaper: an annual service that catches small faults early, and a CP12 renewed ahead of the deadline rather than in a scramble. I offer both together for Southampton landlords, with reminders before the certificate lapses.",
        tags=["#Landlord", "#CP12", "#GasSafetyCertificate", "#PropertyManagement", "#BTL"],
    ),
    # 31 — p121 emergency: carbon monoxide alarm checks
    dict(
        pillar="emergency",
        topic="Carbon monoxide alarms — the checks people skip",
        slug="gas-safety", suffix="co-alarm",
        hint="ai", itype="ai", banner="upper",
        caption="When did you last test it? ⚠️",
        cta=None, extra_cta="Tag someone who definitely hasn't tested theirs.",
        fb="⚠️ Your carbon monoxide alarm — three checks most people never do:\n\n1️⃣ Press the test button monthly. Not 'when you remember'. Monthly.\n2️⃣ Find the expiry date on the back — CO sensors wear out, usually after 5–10 years. An expired alarm looks fine and protects nobody.\n3️⃣ Check the position: roughly head height, in the same room as the gas appliance, but not directly above the boiler or inside a cupboard.\n\nCO has no smell, no colour, no warning. The alarm is the warning. Make sure yours actually works.",
        ig="The alarm that only matters if it works ⚠️\n\nThree CO alarm checks most people skip:\n\n1️⃣ Test button — monthly. Not 'when you remember'\n2️⃣ Expiry date on the back — CO sensors die after 5–10 years. An expired alarm looks fine and protects nobody\n3️⃣ Position — head height, same room as the gas appliance, NOT inside a cupboard or right above the boiler\n\nCarbon monoxide has no smell, no colour, no warning.\n\nThe alarm IS the warning. Make sure yours works.",
        tw="Your CO alarm: test monthly, check the expiry (sensors die after 5–10 yrs), keep it head height in the room with the appliance. ⚠️\n\nCO gives no warning. The alarm IS the warning.",
        gb="Carbon monoxide alarms only protect you if they actually work, and three simple checks are widely skipped. First, press the test button monthly — it takes two seconds. Second, find the expiry date printed on the back: CO sensors degrade and most alarms need replacing after five to ten years, and an expired unit looks identical to a working one. Third, check the position — roughly head height in the same room as the gas appliance, never shut inside a cupboard or mounted directly above the boiler. Carbon monoxide has no smell, colour or taste, so the alarm is your only warning. I check alarm placement and operation as part of every gas safety visit in Southampton.",
        tags=["#CarbonMonoxide", "#COAlarm", "#GasSafety", "#HomeSafety"],
        prompt="SCENE: a warm UK hallway interior, soft afternoon light, photorealistic, shallow depth of field.\nSUBJECT: a white carbon monoxide alarm mounted on a wall at head height, a finger pressing its test button, small green LED visible. Text on a clean navy banner across the upper third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"When did you last test it? ⚠️\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; calm domestic palette, no faces visible, only a hand.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos or brand names on the alarm. Photorealistic, not illustrative.",
    ),
    # 32 — p122 personal: why I stay sole-trader
    dict(
        pillar="personal",
        topic="Why I stay a one-man band",
        slug="plumbing", suffix="sole-trader",
        hint="brand:wes_portrait", itype="brand", banner="lower",
        caption="Just me. That's the point. 👊",
        cta=None, extra_cta="Boiler or plumbing playing up? Send me a WhatsApp video on 07700 155 655.",
        fb="👊 People ask why I haven't taken on a couple of vans and grown the thing. Honest answer? Because then it stops being the thing.\n\nRight now: the person who quotes your job is the person who turns up, does the work, and answers for it afterwards. My name is on every weld, every flue reading, every invoice.\n\nThe trade-off is real — some weeks you might wait a day longer than a big firm would make you wait. What you get back is that nothing about your job gets lost in a handover, because there isn't one.\n\nSmall on purpose.",
        ig="People ask why I don't get a couple more vans and grow it 👊\n\nHonest answer: because then it stops being the thing.\n\nRight now, the person who quotes your job is the person who turns up, does the work, and answers for it afterwards. My name's on every weld, every reading, every invoice.\n\nThe trade-off is real — some weeks you wait a day longer than a big firm would make you.\n\nWhat you get back: nothing gets lost in a handover. Because there isn't one.\n\nSmall on purpose.",
        tw="Why stay a one-man band? Because the person who quotes your job is the person who turns up and answers for it after. 👊\n\nNo handovers. Nothing lost between departments. Small on purpose.",
        gb="Customers occasionally ask why I haven't expanded into a multi-van operation. The honest answer is that staying small is deliberate. As a sole trader, the person who surveys and quotes your job is the same person who turns up, completes the work and stands behind it afterwards — there are no handovers where details get lost, and no gap between who promised and who delivers. The trade-off is honest too: in a busy week you might wait a day longer than a large firm would quote. In return, accountability never gets diluted. One name on the van, one name on the work, across all of Southampton.",
        tags=["#SoleTrader", "#SmallBusiness", "#LocalBusiness", "#HonestTrade"],
    ),
    # 33 — p123 local: North Baddesley
    dict(
        pillar="local",
        topic="Area coverage — North Baddesley",
        slug="power-flush", suffix="north-baddesley",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering North Baddesley 📍",
        cta="SLUDGE", extra_cta=None,
        fb="📍 North Baddesley — you're covered.\n\nA lot of your homes went up in the 70s and 80s, and plenty still run on original pipework. Forty-odd years of fine black sludge settling in the system is why so many radiators out your way run lukewarm at the bottom while the boiler works flat out.\n\n🔥 Power flushing that brings tired systems back to life\n🔧 Boiler repairs and servicing on the same round\n\nIf the house takes forever to warm up, the system's telling you something.",
        ig="North Baddesley, you're covered 📍\n\nLots of your homes went up in the 70s and 80s — many still on original pipework. Forty years of fine black sludge is why so many rads out your way run lukewarm at the bottom while the boiler works flat out.\n\n🔥 Power flushing that brings tired systems back to life\n🔧 Boiler repairs and servicing on the same round\n\nHouse takes forever to warm up? The system's telling you something.",
        tw="North Baddesley 📍 70s/80s homes + original pipework = decades of sludge and lukewarm rads. Power flushing, repairs and servicing — all on the round.",
        gb="North Baddesley is well within my regular coverage. Much of the village's housing dates from the 1970s and 80s, and a good number of homes still run heating through original pipework — which means decades of fine black iron sludge gradually settling through the system. The classic symptoms: radiators lukewarm at the bottom, rooms that take an age to heat, and a boiler working flat out for mediocre results. A power flush clears the accumulated sludge and restores proper circulation, and I handle boiler repairs and annual servicing on the same round. If your North Baddesley home takes forever to warm up, the system is telling you something worth hearing.",
        tags=["#NorthBaddesley", "#SO52", "#PowerFlush", "#CentralHeating"],
    ),
    # 34 — p124 tips: stopcock maintenance
    dict(
        pillar="tips",
        topic="Turn your stopcock once a year — here's why",
        slug="plumbing", suffix="stopcock-turn",
        hint="asset:plumbing", itype="asset", banner="upper",
        caption="Turn your stopcock once a year 🔧",
        cta=None, extra_cta="Save this — then go and actually do it this weekend.",
        fb="🔧 The most important 60 seconds of home maintenance nobody does:\n\nOnce a year, find your stopcock (usually under the kitchen sink), turn it fully off, then fully on, then back a quarter turn.\n\nWhy? Stopcocks seize. They sit untouched for a decade, then the night a pipe bursts you're heaving on a valve that won't budge while water pours through the ceiling.\n\nThe quarter turn back keeps it from jamming at the fully-open end too.\n\n60 seconds a year. It only matters on the worst night of your home-owning life — which is exactly why it matters.",
        ig="The most important 60 seconds of home maintenance nobody does 🔧\n\nOnce a year: find your stopcock (usually under the kitchen sink). Turn it fully off. Fully on. Then back a quarter turn.\n\nWhy? Stopcocks seize. They sit untouched for a decade — then the night a pipe bursts, you're heaving on a jammed valve while water pours through the ceiling.\n\nThe quarter turn back stops it jamming at the open end too.\n\n60 seconds a year, and it only matters on the worst night of your home-owning life. Which is exactly why it matters.",
        tw="Once a year: turn your stopcock fully off, fully on, then back a quarter turn. 🔧\n\nSeized stopcocks are found at the worst moment — mid-burst, water through the ceiling. 60 seconds of prevention.",
        gb="Here's a sixty-second maintenance job that almost nobody does and everybody should. Once a year, find your stopcock — usually under the kitchen sink — and turn it fully off, then fully on, then back a quarter of a turn. The reason is simple: stopcocks seize. They sit untouched for years, and the moment you discover yours has jammed is invariably mid-emergency, heaving at an immovable valve while water comes through a ceiling. The annual exercise keeps the mechanism free, and finishing a quarter turn back from fully open prevents it jamming at that end of its travel too. If yours is already seized or weeping, replacing it is a quick job. Plumbing across Southampton.",
        tags=["#PlumbingTips", "#Stopcock", "#HomeMaintenance", "#BurstPipe"],
    ),
    # 35 — p125 work: tap cartridge job story
    dict(
        pillar="work",
        topic="Job story — twenty minutes, drip gone",
        slug="tap-repair", suffix="tap-cartridge-job",
        hint="work:tap_install", itype="work", banner="lower",
        caption="20 minutes. Drip gone. 🚿",
        cta="QUOTE", extra_cta=None,
        fb="🚿 Kitchen mixer in Freemantle, dripping for months. The owner had been quoted for a whole new tap by someone who 'doesn't really do repairs'.\n\nIt didn't need a new tap. It needed a cartridge — the ceramic insert that actually does the shutting-off. Twenty minutes, drip gone, original tap saved.\n\n💡 Tip: WhatsApp me a photo of your tap before I come. Make and shape usually tell me which cartridge to have in the van, so it's one visit, not two.\n\nNot everything needs replacing. Sometimes it just needs someone who repairs things.",
        ig="Dripping for months. Fixed in twenty minutes. 🚿\n\nKitchen mixer in Freemantle — the owner had been quoted for a whole new tap by someone who 'doesn't really do repairs'.\n\nIt didn't need a new tap. It needed a cartridge: the little ceramic insert that does the actual shutting-off. Twenty minutes, drip gone, original tap saved.\n\n💡 WhatsApp me a photo of your tap first — make and shape usually tell me which cartridge to bring. One visit, not two.\n\nNot everything needs replacing.",
        tw="Kitchen tap in Freemantle, dripping for months. Quoted elsewhere for a full replacement. 🚿\n\nIt needed a £-of-parts cartridge swap. 20 minutes, drip gone, tap saved.\n\nNot everything needs replacing.",
        gb="A recent small job that says a lot: a kitchen mixer tap in Freemantle had been dripping for months, and the owner had been quoted for a complete replacement by a firm that 'doesn't really do repairs'. The tap didn't need replacing — it needed a new cartridge, the ceramic insert inside the handle that does the actual shutting-off. Twenty minutes later the drip was gone and the original tap saved. A useful tip: send a WhatsApp photo of your tap before the visit. The make and shape usually identify the right cartridge, so it's carried in the van and fixed in one visit rather than two. Tap repairs across Southampton.",
        tags=["#TapRepair", "#Freemantle", "#PlumbingRepairs", "#FixedNotReplaced"],
    ),
    # 36 — p126 cost_reveal: blocked-sink callout reality
    dict(
        pillar="cost_reveal",
        topic="What a blocked-sink callout actually buys",
        slug="plumbing", suffix="blocked-sink",
        hint="ai", itype="ai", banner="lower",
        caption="What a blocked-sink callout buys 💷",
        cta="QUOTE", extra_cta=None,
        fb="💷 Blocked sink callouts — here's what you're actually paying for. (Hint: it's not the plunging.)\n\nIt's the diagnosis. Is the blockage at the trap, or a metre down the pipe? Grease, scale, or a sagging waste run that will block again next month no matter what's poured down it?\n\nClear the symptom and you'll meet the same blockage again in four weeks. Find the cause and it stays gone.\n\n⚠️ Be careful with rock-bottom 'unblocking specials' — clearing the trap takes minutes, and if the real problem is further down, you've paid to postpone it.",
        ig="What a blocked-sink callout actually buys 💷\n\nNot the plunging. The diagnosis.\n\nIs it at the trap — or a metre down the line? Grease, scale, or a sagging waste pipe that'll re-block monthly no matter what's poured down it?\n\nClear the symptom: same blockage, four weeks later.\nFind the cause: it stays gone.\n\n⚠️ Rock-bottom 'unblocking specials' clear the trap in minutes. If the real problem is further down, you've paid to postpone it.",
        tw="A blocked-sink callout isn't buying the plunge — it's buying the diagnosis. 💷\n\nSymptom cleared = same blockage in 4 weeks.\nCause found = stays gone.\n\nCheap 'unblock specials' often just postpone it.",
        gb="When you pay for a blocked-sink callout, the value isn't in the plunging — it's in the diagnosis. A proper visit establishes where the blockage actually sits: at the trap, or further down the run. It identifies what it's made of — grease, scale, or debris collecting in a sagging waste pipe that will re-block every month no matter what's poured down it. Clearing the symptom without finding the cause means meeting the same blockage again within weeks, which is how rock-bottom 'unblocking specials' end up expensive. I clear the blockage, explain the cause, and tell you honestly whether it's a one-off or something structural. Plumbing repairs across Southampton.",
        tags=["#BlockedSink", "#PlumbingRepairs", "#PlumbingTips", "#HonestTrade"],
        prompt="SCENE: a UK kitchen, natural daylight, photorealistic, eye-level view of a stainless steel sink.\nSUBJECT: a kitchen sink with water standing and refusing to drain, a single small ripple on the surface, washing-up bowl set aside. Text on a clean navy banner across the lower third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"What a blocked-sink callout buys 💷\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; ordinary domestic palette, no people, no brand logos.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos. Photorealistic, not illustrative.",
    ),
    # 37 — p127 local mascot: Southampton docks
    dict(
        pillar="local",
        topic="Where's Wes today? — Southampton docks",
        slug="boiler-service", suffix="wes-docks",
        hint="asset:logo_mascot", itype="asset", banner="lower",
        caption="Where's Wes today? 📍 The docks",
        cta=None, extra_cta="Final stop next week — guess where he ends the tour 👇",
        fb="📍 Where's Wes today? Down at the docks!\n\nStop three on the tour, and the little fella's found the biggest thing he's ever seen. That ship probably has a hot water system the size of a house. Wes would love a look at the plant room. ⚓\n\nFun fact for the day: those cruise ships get serviced on a strict schedule, every time, no exceptions. Your boiler deserves the same respect — it just asks once a year.\n\nOne more landmark to go. Guesses below 👇",
        ig="Where's Wes today? Stop three: the docks ⚓\n\nThe little fella's found the biggest thing he's ever seen. That ship probably has a hot water system the size of a house — Wes would LOVE a look at the plant room.\n\nFun fact: cruise ships get serviced on a strict schedule. Every time. No exceptions.\n\nYour boiler deserves the same respect — and it only asks once a year. 😄\n\nOne landmark left on the tour. Guesses below 👇",
        tw="Where's Wes today? 📍 The docks — eyeing up a cruise ship's plant room. ⚓\n\nThose ships get serviced on schedule, no exceptions. Your boiler only asks once a year. 😄",
        gb="Stop three on the Better Call Wes mascot tour: Southampton docks, where the little fella is admiring the biggest piece of engineering in the city. There's a serious point hiding in the fun — cruise ships run on strict, non-negotiable maintenance schedules, because failures at sea aren't an option. Home boilers deserve a fraction of that respect: one proper service a year, with flue gas analysis, pressure checks and a filter clean, prevents the majority of winter breakdowns. Boiler servicing, repairs and heating work across every Southampton postcode from one local Gas Safe registered engineer. One landmark left on the tour — follow along.",
        tags=["#Southampton", "#SouthamptonDocks", "#CruiseShip", "#SouthamptonLife", "#WheresWes"],
        prompt="TASK: Place the cartoon mascot character from the source image into a new scene.\n\nSOURCE: The input image is the Better Call Wes logo featuring a cartoon mascot of a Black African plumber in a navy polo holding a wrench and phone. Preserve the mascot's exact appearance, style, colours, and proportions.\n\nSCENE: A photorealistic view of Southampton docks on a clear morning — a huge white cruise ship berthed at the cruise terminal, harbour water in the foreground, port cranes and terminal buildings behind — with the cartoon mascot standing playfully in the foreground giving a thumbs up — deliberate cartoon-on-photo contrast, like a mascot sticker on a postcard.\n\nCHANGE: Add ONE caption banner in the lower third.\n- Banner style: solid rectangle, brand navy #0A2540, 88% opacity, full-width, 14% of image height, clean edges\n- Small orange #FF6B00 accent bar, 4px, along the top edge of the banner\n- Headline (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Where's Wes today? 📍 The docks\"\n- Typography: bold sans-serif, white, centred, generous kerning, optically sized for social-feed legibility\n\nCONSTRAINTS: Render the headline verbatim. No other text anywhere in the image. Keep the mascot's identity, colours and proportions exactly as in the source. No watermark. No extra logos. Do not render any real cruise line branding on the ship.\n\nUSE CASE: Instagram social post, square 1:1, 1080x1080.",
    ),
    # 38 — p128 personal: the van morning routine
    dict(
        pillar="personal",
        topic="The 5:45am van routine",
        slug="boiler-repair", suffix="van-routine",
        hint="asset:van", itype="asset", banner="lower",
        caption="5:45am. Van loaded. ☕",
        cta=None, extra_cta="Ever wondered what's actually in a heating engineer's van? Ask away 👇",
        fb="☕ 5:45am. Kettle first. Then the van.\n\nSame routine every working morning:\n\n🔋 Flue gas analyser — charged and calibrated\n📦 Parts bins restocked from whatever yesterday used up\n🗒️ First job's likely parts moved up behind the seat\n🧤 Dust sheets, gloves, overshoes back in their spots\n\nTen minutes of boring preparation. But it's the difference between 'fixed by lunch' and 'I'll have to order that in' — and most of the time, that ten minutes was decided before your boiler even broke.",
        ig="5:45am. Kettle first. Then the van. ☕\n\nSame routine, every working morning:\n\n🔋 Flue gas analyser — charged, calibrated\n📦 Parts bins restocked from whatever yesterday used\n🗒️ First job's likely parts moved up behind the seat\n🧤 Dust sheets, gloves, overshoes back in their spots\n\nTen boring minutes. But they're the difference between 'fixed by lunch' and 'I'll have to order that in'.\n\nMost same-day fixes are decided before the boiler even breaks.",
        tw="5:45am van routine: analyser charged, parts restocked, first job's bits behind the seat. ☕\n\nTen boring minutes — but most 'fixed by lunch' jobs are decided before your boiler even breaks.",
        gb="Most mornings start the same way: kettle on at 5:45, then ten minutes with the van before the first job. The flue gas analyser goes on charge overnight and gets checked; parts bins are restocked to replace whatever yesterday's jobs used; the likely parts for the first appointment move up behind the seat; dust sheets, gloves and overshoes go back in their places. It's unglamorous, but that routine is why so many repairs finish the same day — the difference between 'fixed by lunch' and 'I'll need to order that in' is usually decided on the driveway at dawn, not at your house. Boiler repairs and servicing across Southampton.",
        tags=["#TradesLife", "#VanLife", "#HeatingEngineerLife", "#MorningRoutine"],
    ),
    # 39 — p129 tips: bathroom extractor and damp
    dict(
        pillar="tips",
        topic="Your extractor fan is the cheapest mould prevention you own",
        slug="shower-repair", suffix="extractor-damp",
        hint="asset:shower", itype="asset", banner="upper",
        caption="Your extractor fan fights mould 💨",
        cta=None, extra_cta="Save this if your bathroom mirror stays foggy.",
        fb="💨 Black mould creeping into bathroom corners isn't a cleaning problem. It's a moisture problem — and your extractor fan is the first line of defence.\n\nGet the basics right:\n✅ Fan ON during every shower, and 15 minutes after — that's when most of the moisture is still hanging in the air\n✅ Door CLOSED while it runs, so it pulls air out instead of from the hallway\n✅ Mirror still fogged 10 minutes after a shower? The fan is too weak, clogged with dust, or just for show\n\n⚠️ And if damp keeps returning in ONE spot — wall, ceiling, under the floor — rule out a small leak before you blame condensation.",
        ig="Black mould in the bathroom corners? That's not a cleaning problem 💨\n\nIt's a moisture problem — and the extractor fan is your first line of defence:\n\n✅ ON during every shower + 15 mins after\n✅ Door CLOSED while it runs (so it pulls air OUT, not from the hallway)\n✅ Mirror still foggy 10 mins after a shower = fan too weak, clogged, or decorative\n\n⚠️ Damp returning in ONE spot — wall, ceiling, floor? Rule out a small leak before blaming condensation.",
        tw="Bathroom mould isn't a cleaning problem — it's a moisture problem. 💨\n\nFan on during + 15 min after showers, door closed while it runs. Mirror still foggy after 10 mins? Your fan's not doing its job.",
        gb="Recurring black mould in bathroom corners is rarely about cleaning — it's about moisture, and the extractor fan is the cheapest defence you own. Used properly, it should run during every shower and for fifteen minutes afterwards, with the door closed so it draws moist air out rather than pulling dry air through from the hallway. A simple test: if the mirror is still fogged ten minutes after a shower, the fan is too weak, clogged with dust, or not actually extracting. One important caveat — damp that keeps returning in a single spot on a wall, ceiling or floor may be a small plumbing leak rather than condensation, and that's worth ruling out properly. Bathroom and shower work across Southampton.",
        tags=["#BathroomTips", "#Mould", "#DampPrevention", "#HomeTips"],
    ),
    # 40 — p130 trust: review card #2
    dict(
        pillar="trust",
        topic="What a review means to a one-man business",
        slug="boiler-repair", suffix="real-review-2",
        hint="review_card", itype="review_card", banner="lower",
        caption="Real review ⭐",
        cta=None, extra_cta=None,
        prerendered="review_cards/review-00-peter.png",
        fb="🙏 \"Highly recommended — and that doesn't come easily from me.\"\n\nThat line, from Peter's review, has stuck with me. He's right not to hand recommendations out easily. Nobody should.\n\nThere's no marketing department here. No sales team. When you're a one-man business, a few honest sentences from a real customer do more than any advert ever could — they're the reason the phone rings at all.\n\nSo to everyone who's taken five minutes to write one: thank you. It matters more than you know.",
        ig="\"Highly recommended — and that doesn't come easily from me.\" 🙏\n\nThat line from Peter's review stuck with me. He's right not to hand out recommendations easily. Nobody should.\n\nThere's no marketing department here. No sales team. For a one-man business, a few honest sentences from a real customer do more than any advert could — they're the reason the phone rings at all.\n\nTo everyone who's taken five minutes to write one: thank you. It matters more than you know.",
        tw="\"Highly recommended — and that doesn't come easily from me.\" 🙏\n\nFor a one-man business, a few honest sentences from a real customer beat any advert. Thank you to everyone who's left one.",
        gb="\"Highly recommended — and that doesn't come easily from me.\" That line from a recent customer review has stayed with me, because he's right: recommendations shouldn't come easily. For a sole trader there's no marketing department and no sales team — a few honest sentences from a real customer are worth more than any advertising, and they're a large part of why the phone rings at all. So thank you, sincerely, to every Southampton customer who has taken five minutes to share their experience. If your boiler or heating needs looking at, I'd be glad to earn the same words from you.",
        tags=["#CustomerReview", "#ThankYou", "#SmallBusiness", "#FiveStars"],
        prompt="",
    ),
]
