# Posts 41-60 of the 60-post batch (p131-p150).

POSTS_C = [
    # 41 — p131 cost_reveal: what an old boiler adds to the gas bill
    dict(
        pillar="cost_reveal",
        topic="What an old inefficient boiler quietly adds to your gas bill",
        slug="new-boiler", suffix="old-boiler-cost",
        hint="asset:boiler", itype="asset", banner="upper",
        caption="Your old boiler's hidden bill 💷",
        cta="QUOTE", extra_cta=None,
        fb="💷 Your old boiler has a second bill you never see itemised.\n\nA 15-to-20-year-old non-condensing boiler turns a worryingly large slice of every pound of gas straight into wasted heat up the flue. A modern condensing boiler recovers most of that — same house, same thermostat, hundreds less burned per year in many homes.\n\nQuick checks that yours is in the wasteful bracket:\n🔥 A permanent pilot light burning day and night\n📅 Installed before roughly 2005\n🌡️ The flue blows hot — that's literally your money leaving\n\nI'm not in the business of selling boilers people don't need. But if yours predates the iPhone, the maths deserves ten minutes of your time.",
        ig="Your old boiler has a second bill 💷\n\nA 15–20 year old non-condensing boiler sends a worrying slice of every pound of gas straight up the flue as wasted heat. A modern condensing one recovers most of it — same house, same thermostat, hundreds less burned a year in many homes.\n\nSigns yours is in the wasteful bracket:\n🔥 Permanent pilot light burning day and night\n📅 Installed before ~2005\n🌡️ Flue blows hot — that's literally money leaving\n\nIf your boiler predates the iPhone, the maths deserves ten minutes.",
        tw="A 15–20 yr old boiler sends a big slice of every £ of gas straight up the flue. 💷\n\nPermanent pilot light? Pre-2005 install? The replacement maths deserves ten minutes of your time.",
        gb="Older boilers carry a cost that never appears as a line item: waste. A fifteen-to-twenty-year-old non-condensing boiler loses a significant share of every pound of gas as heat straight up the flue, where a modern condensing model recovers most of it — same house, same thermostat, but in many homes hundreds of pounds less burned per year. Signs your boiler sits in the wasteful bracket: a permanent pilot light, an installation date before roughly 2005, or a flue that blows noticeably hot. I'm not in the business of selling boilers people don't need — plenty of older units have life left — but if yours predates the iPhone, the replacement maths is worth ten honest minutes. Free, no-pressure quotes in Southampton.",
        tags=["#NewBoiler", "#EnergyBills", "#BoilerUpgrade", "#GasBill"],
    ),
    # 42 — p132 local: West End
    dict(
        pillar="local",
        topic="Area coverage — West End",
        slug="boiler-service", suffix="west-end",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering West End 📍",
        cta="SERVICE", extra_cta=None,
        fb="📍 West End — you're on the round.\n\nHome of the Utilita Bowl, the country park… and a lot of 80s and 90s estates whose boilers are quietly entering their difficult years.\n\n🔥 Annual servicing that actually inspects things — flue gases, pressures, expansion vessel, filter\n🔧 Repairs with a £100 diagnostic, most minor fixes done on the spot\n🚐 Minutes up the road, not dispatched from a depot\n\nIf the boiler's been making new noises since last winter, don't wait for it to pick its moment.",
        ig="West End, you're covered 📍\n\nHome of the Utilita Bowl, the country park… and a lot of 80s/90s estates whose boilers are quietly entering their difficult years.\n\n🔥 Proper servicing — flue gases, pressures, expansion vessel, filter\n🔧 Repairs with a £100 diagnostic\n🚐 Minutes up the road, not a depot dispatch\n\nBoiler making new noises since last winter? Don't let it pick its moment.",
        tw="West End 📍 On the round — proper boiler servicing and repairs for those 80s/90s estates whose boilers are entering their difficult years. Minutes away, not a depot dispatch.",
        gb="West End is firmly on my regular round — from the streets around the Utilita Bowl to the estates bordering the country park. A lot of the area's 1980s and 90s housing is now running boilers in their difficult years, where small faults start arriving more often and an annual service earns its keep. Mine is a proper inspection: flue gas analysis, gas pressure checks, expansion vessel test and magnetic filter clean, with photos of anything found. Repairs come with a £100 diagnostic that covers most minor fixes on the spot. Local genuinely means local here — minutes up the road, same engineer every time.",
        tags=["#WestEnd", "#SO30", "#BoilerService", "#LocalTrades"],
    ),
    # 43 — p133 work: CP12 job story
    dict(
        pillar="work",
        topic="Job story — a landlord CP12 morning, done properly",
        slug="cp12", suffix="cp12-job",
        hint="work:gas_inspection", itype="work", banner="lower",
        caption="Landlord cert, done properly 📋",
        cta="SERVICE", extra_cta=None,
        fb="📋 CP12 morning for a Portswood landlord this week. Here's what 'just a certificate' actually involves when it's done properly:\n\n✅ Tightness test at the meter — any leak shows up before anything else happens\n✅ Boiler: flue gas analysis, gas rate, safety devices\n✅ Hob: flame picture, connections, stability\n✅ Ventilation and flue routes checked\n✅ Certificate emailed to landlord and agent before lunch\n\nTenants protected, landlord legal, no corners cut. If your renewal date is creeping up, book it before the changeover season rush.",
        ig="'Just a certificate'? Here's what a proper CP12 involves 📋\n\nA Portswood landlord's morning this week:\n\n✅ Tightness test at the meter — leaks show up first\n✅ Boiler: flue gas analysis, gas rate, safety devices\n✅ Hob: flame picture, connections, stability\n✅ Ventilation + flue routes checked\n✅ Cert emailed to landlord and agent before lunch\n\nTenants protected. Landlord legal. No corners cut.\n\nRenewal creeping up? Book ahead of the changeover rush.",
        tw="A proper CP12 isn't 'just a certificate' 📋 Tightness test, flue analysis, gas rate, hob checks, ventilation — cert emailed before lunch. Tenants protected, landlord legal.",
        gb="A landlord gas safety certificate is sometimes treated as a formality — here's what a proper one involves, from a recent morning in Portswood. The visit starts with a tightness test at the meter, so any leak in the installation shows itself before anything else happens. The boiler gets flue gas analysis, a gas rate check and verification of its safety devices; the hob is checked for flame picture, connection integrity and stability; ventilation and flue routes are inspected. The CP12 was emailed to landlord and letting agent before lunch. Tenants protected, landlord legally covered, nothing skimmed. Southampton landlords — book renewals ahead of tenancy changeover season.",
        tags=["#CP12", "#Landlord", "#GasSafetyCertificate", "#Portswood", "#LettingAgents"],
    ),
    # 44 — p134 emergency: boiler dies on a Friday night
    dict(
        pillar="emergency",
        topic="Boiler dies on a Friday night — what to actually do",
        slug="boiler-repair", suffix="friday-boiler",
        hint="brand:wes_with_phone", itype="brand", banner="upper",
        caption="Boiler died Friday night? 📲",
        cta="QUOTE", extra_cta=None,
        fb="📲 Boiler dies at 9pm on a Friday. Before you panic-Google, do this:\n\n1️⃣ Check the pressure gauge — under 1 bar? Top up via the filling loop and reset. This alone fixes a surprising number of 'dead' boilers.\n2️⃣ One reset only. If it locks out again, stop — repeated resets can mask the fault.\n3️⃣ Got a hot water cylinder? The immersion heater is your backup for showers.\n4️⃣ Heat the rooms you're actually in, close the doors.\n5️⃣ Send me a WhatsApp video of the boiler and its fault code tonight — I'll pick it up as soon as I can, often with the right part lined up before the visit.\n\nA video tonight usually beats a cold queue on Monday.",
        ig="Boiler dies. 9pm. Friday. Here's the playbook: 📲\n\n1️⃣ Check pressure — under 1 bar? Top up via the filling loop, reset. Fixes a surprising number of 'dead' boilers\n2️⃣ ONE reset only — repeated resets mask the fault\n3️⃣ Hot water cylinder? The immersion heater is your shower backup\n4️⃣ Heat only the rooms you're in, doors closed\n5️⃣ WhatsApp me a video of the boiler + fault code tonight — I pick videos up as soon as I can, often with the right part lined up before the visit\n\nA video tonight beats a cold queue on Monday.",
        tw="Boiler dead, Friday 9pm? Check pressure (top up if under 1 bar), reset ONCE, immersion for hot water, heat one room. 📲\n\nThen WhatsApp a video of the fault code — right part, first visit.",
        gb="When a boiler dies on a Friday night, a few calm steps make the weekend manageable. First check the pressure gauge: if it reads under 1 bar, top up via the filling loop and reset — this alone revives a surprising number of 'dead' boilers. Reset once only; repeated resets can mask the underlying fault. If you have a hot water cylinder, the immersion heater covers showers in the meantime, and heating just the rooms you're using keeps things bearable. Then send a WhatsApp video of the boiler and its fault code to 07700 155 655 — I pick videos up as soon as I'm able, and a video sent Friday night often means the right part is lined up before the visit.",
        tags=["#BoilerBreakdown", "#EmergencyTips", "#BoilerRepair", "#WhatsAppFix"],
    ),
    # 45 — p135 tips: TRV settings explained
    dict(
        pillar="tips",
        topic="TRV numbers explained — they're temperatures, not power",
        slug="heating-controls", suffix="trv-settings",
        hint="asset:radiator", itype="asset", banner="upper",
        caption="What the numbers actually mean 🌡️",
        cta=None, extra_cta="Save this — your spare room is on the wrong number right now.",
        fb="🌡️ Those numbers on your radiator valves aren't volume knobs. They're target temperatures:\n\n❄️ * (frost) ≈ 7°C — pipes protected, room cold\n2️⃣ ≈ 17°C — perfect for bedrooms (you sleep better cooler)\n3️⃣ ≈ 20°C — the living-room sweet spot\n5️⃣ ≈ 25°C+ — a greenhouse\n\nThe valve isn't 'pushing harder' on 5 — it just keeps heating until the room hits a higher temperature, then stops.\n\n💡 So cranking every rad to 5 doesn't heat the house faster. It just heats it longer, and you pay for the difference.",
        ig="Radiator valve numbers aren't volume knobs 🌡️\n\nThey're target temperatures:\n\n❄️ * (frost) ≈ 7°C — pipe protection\n2️⃣ ≈ 17°C — bedrooms (you sleep better cooler)\n3️⃣ ≈ 20°C — living room sweet spot\n5️⃣ ≈ 25°C+ — a greenhouse\n\nThe valve isn't 'pushing harder' on 5. It just keeps heating until the room is hotter, then stops.\n\n💡 Cranking every rad to 5 doesn't heat the house faster — it heats it LONGER. And you pay for the difference.",
        tw="TRV numbers are temperatures, not power. 🌡️\n\n* ≈ 7°C · 2 ≈ 17°C (bedrooms) · 3 ≈ 20°C (lounge) · 5 ≈ greenhouse\n\nMax on every rad doesn't heat the house faster — just longer. You pay the difference.",
        gb="The numbers on thermostatic radiator valves are widely misunderstood — they're target room temperatures, not power levels. As a rough guide, the frost symbol holds about 7°C to protect pipework, setting 2 gives around 17°C (ideal for bedrooms, where most people sleep better cooler), setting 3 is roughly 20°C for living spaces, and 5 is well over 25°C. A valve on 5 isn't pushing heat harder; it simply keeps the radiator on until the room reaches a higher temperature. That's why turning every radiator to maximum doesn't warm the house faster — it just runs the heating longer, at your expense. Set each room to its job and the savings follow. Heating controls advice across Southampton.",
        tags=["#TRV", "#HeatingTips", "#RadiatorTips", "#EnergySaving"],
    ),
    # 46 — p136 cost_reveal: a weak shower is a cheap fix
    dict(
        pillar="cost_reveal",
        topic="A dribbling shower rarely needs a new bathroom",
        slug="shower-repair", suffix="weak-shower",
        hint="asset:shower", itype="asset", banner="lower",
        caption="A weak shower is a cheap fix 🚿",
        cta="QUOTE", extra_cta=None,
        fb="🚿 A dribbling shower makes people think 'new bathroom money'. It's almost never that.\n\nThe usual suspects, cheapest first:\n\n1️⃣ Scaled shower head — unscrew it, overnight vinegar soak, costs pennies\n2️⃣ Clogged inlet filters — quick strip and clean\n3️⃣ Scaled or worn cartridge inside the valve — the most common 'proper' fix, done within the hour\n4️⃣ Genuine pressure problem in the house — rarer, needs a real diagnosis\n\nNotice what's NOT on the list? Ripping out the bathroom.\n\nMost weak showers are an hour's work, not a renovation.",
        ig="A dribbling shower is NOT 'new bathroom money' 🚿\n\nThe usual suspects, cheapest first:\n\n1️⃣ Scaled head — overnight vinegar soak, costs pennies\n2️⃣ Clogged inlet filters — strip and clean\n3️⃣ Worn cartridge in the valve — the most common real fix, done within the hour\n4️⃣ Genuine house pressure problem — rarer, needs proper diagnosis\n\nWhat's not on the list: ripping out your bathroom.\n\nMost weak showers are an hour's work, not a renovation.",
        tw="A dribbling shower isn't 'new bathroom money'. 🚿\n\nUsually: scaled head (vinegar, pennies), clogged filters, or a worn valve cartridge — an hour's work. Diagnose before you renovate.",
        gb="A weak, dribbling shower sends many people's minds straight to renovation budgets — and it's almost never necessary. The usual causes, cheapest first: a limescaled shower head, fixed with an overnight vinegar soak; clogged inlet filters, a quick strip-and-clean; or a scaled and worn cartridge inside the shower valve, which is the most common genuine fault and typically replaced within the hour. A true pressure problem affecting the whole house is rarer and needs proper diagnosis rather than guesswork. In Southampton's hard water, scale is the culprit more often than not. Before anyone talks you into ripping out a bathroom, get the actual fault identified — most weak showers are an hour's work.",
        tags=["#ShowerRepair", "#BathroomTips", "#HardWater", "#PlumbingRepairs"],
    ),
    # 47 — p137 personal: why I ask for a video first
    dict(
        pillar="personal",
        topic="Why I ask for a WhatsApp video before quoting",
        slug="boiler-repair", suffix="video-first",
        hint="brand:wes_with_phone", itype="brand", banner="lower",
        caption="Why I ask for a video first 📲",
        cta=None, extra_cta="Try it: 10 seconds of your boiler to 07700 155 655.",
        fb="📲 'Can you just send me a quick video of it?'\n\nI ask almost everyone this, and here's why: ten seconds of your boiler doing its thing tells me more than ten minutes of description. The fault code, the noise, the pressure gauge, what the flame does — it's all right there.\n\nWhat that does for you:\n✅ I can look between jobs and come back with a real answer, not a guess\n✅ The right part goes in the van BEFORE the visit\n✅ Plenty of small things get solved over message — no callout at all\n\nIt's the closest thing to a free diagnosis you'll find.",
        ig="'Can you send me a quick video of it?' 📲\n\nI ask almost everyone this. Ten seconds of your boiler doing its thing beats ten minutes of describing it — the fault code, the noise, the gauge, the flame. It's all right there.\n\nWhat it does for you:\n✅ I look between jobs and reply with a real answer, not a guess\n✅ The right part goes in the van BEFORE the visit\n✅ Plenty of small stuff gets solved over message — no callout at all\n\nClosest thing to a free diagnosis you'll find.",
        tw="Ten seconds of video beats ten minutes of describing the fault. 📲\n\nThe code, the noise, the gauge — all there. Right part in the van first visit; plenty solved with no callout at all.",
        gb="Almost every enquiry I receive gets the same request: 'send me a quick video of it'. There's a good reason. Ten seconds of footage — the fault code, the noise it's making, the pressure gauge, what the flame does — tells me more than ten minutes of description over the phone. For customers, the benefits are concrete: I can review the video between jobs and respond with a genuine assessment rather than a guess; the right part goes in the van before the visit, which is how most repairs get finished in one trip; and a fair number of small issues get resolved over message with no callout at all. WhatsApp 07700 155 655 — it's the closest thing to a free diagnosis you'll find.",
        tags=["#WhatsApp", "#BoilerRepair", "#SmartService", "#HeatingEngineerLife"],
    ),
    # 48 — p138 local mascot: Southampton Common
    dict(
        pillar="local",
        topic="Where's Wes today? — Southampton Common",
        slug="central-heating", suffix="wes-common",
        hint="asset:logo_mascot", itype="asset", banner="lower",
        caption="Where's Wes today? 📍 The Common",
        cta=None, extra_cta="Should the tour continue? Vote with a comment — and nominate the next stop 👇",
        fb="📍 Where's Wes today? Final stop: Southampton Common!\n\n326 acres, ancient trees, the paddling pool, the ducks — and after a thorough inspection, the little fella can confirm: not a single radiator on the entire Common. Shocking. 😄\n\nThat wraps the landmark tour — Bargate, Itchen Bridge, the docks, and now the Common. Thanks for playing along, Southampton.\n\nShould he keep going? Nominate the next location in the comments — best suggestion gets a visit. 👇",
        ig="Where's Wes today? Final stop: the Common 🌳\n\n326 acres. Ancient trees. The paddling pool. The ducks.\n\nAnd after a thorough inspection, the little fella confirms: not a single radiator on the entire Common. Shocking. 😄\n\nThat wraps the tour — Bargate ✅ Itchen Bridge ✅ Docks ✅ Common ✅\n\nThanks for playing along, Southampton.\n\nShould he keep going? Nominate the next stop — best suggestion gets a visit 👇",
        tw="Where's Wes today? 📍 Southampton Common — 326 acres inspected, zero radiators found. Shocking. 😄\n\nThat wraps the landmark tour. Nominate the next stop and he might keep going.",
        gb="The final stop on the Better Call Wes mascot tour of Southampton: the Common. All 326 acres inspected, and the little fella reports back — ancient woodland, the paddling pool, plenty of ducks, and not one radiator on the entire site. The tour has taken in the Bargate, the Itchen Bridge, the docks and now the Common, and the serious bit underneath the fun stays the same: central heating, boiler and plumbing work across every Southampton postcode from one local Gas Safe registered engineer with honest pricing. Thanks to everyone who followed along — nominations for future stops are open in the comments on our social pages.",
        tags=["#Southampton", "#SouthamptonCommon", "#LocalBusiness", "#SouthamptonLife", "#WheresWes"],
        prompt="TASK: Place the cartoon mascot character from the source image into a new scene.\n\nSOURCE: The input image is the Better Call Wes logo featuring a cartoon mascot of a Black African plumber in a navy polo holding a wrench and phone. Preserve the mascot's exact appearance, style, colours, and proportions.\n\nSCENE: A photorealistic view of Southampton Common on a sunny day — wide green parkland with mature oak trees, a path curving through the grass, dog walkers softly blurred in the far distance, blue sky with light clouds — with the cartoon mascot standing playfully in the foreground giving a thumbs up — deliberate cartoon-on-photo contrast, like a mascot sticker on a postcard.\n\nCHANGE: Add ONE caption banner in the lower third.\n- Banner style: solid rectangle, brand navy #0A2540, 88% opacity, full-width, 14% of image height, clean edges\n- Small orange #FF6B00 accent bar, 4px, along the top edge of the banner\n- Headline (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Where's Wes today? 📍 The Common\"\n- Typography: bold sans-serif, white, centred, generous kerning, optically sized for social-feed legibility\n\nCONSTRAINTS: Render the headline verbatim. No other text anywhere in the image. Keep the mascot's identity, colours and proportions exactly as in the source. No watermark. No extra logos.\n\nUSE CASE: Instagram social post, square 1:1, 1080x1080.",
    ),
    # 49 — p139 tips: gas hob flame colour
    dict(
        pillar="tips",
        topic="What your gas hob's flame colour is telling you",
        slug="gas-safety", suffix="flame-colour",
        hint="work:gas_inspection", itype="work", banner="upper",
        caption="Your hob flame should be blue 🔵",
        cta="SERVICE", extra_cta=None,
        fb="🔵 Quick kitchen safety check you can do tonight: look at your hob's flame.\n\n✅ Crisp blue with a steady cone = clean, complete combustion. All good.\n⚠️ Lazy yellow or orange tips, flames that lift and flutter, or soot on your pan bottoms = incomplete combustion. That means the burner needs attention — and incomplete combustion is what produces carbon monoxide.\n\nA yellow flame isn't a 'keep an eye on it'. Stop using that burner and get it checked.\n\n(And if you ever smell gas: 0800 111 999, free, 24/7 — before anything else.)",
        ig="Look at your hob flame tonight 🔵\n\n✅ Crisp blue, steady cone = clean combustion. All good\n⚠️ Lazy yellow/orange tips, fluttering flames, soot on pan bottoms = incomplete combustion — the thing that produces carbon monoxide\n\nA yellow flame isn't a 'keep an eye on it'. Stop using that burner. Get it checked.\n\n(Smell gas? 0800 111 999 — free, 24/7, before anything else.)",
        tw="Check your hob flame: crisp blue = good. Lazy yellow/orange, fluttering, sooty pans = incomplete combustion — the thing that makes carbon monoxide. 🔵\n\nStop using that burner. Get it checked.",
        gb="Here's a kitchen safety check that takes five seconds: look at the colour of your gas hob's flame. A healthy burner shows a crisp blue flame with a steady cone — that's clean, complete combustion. Lazy yellow or orange tips, flames that lift and flutter, or soot collecting on the bottom of your pans all point to incomplete combustion, which is both inefficient and the process that produces carbon monoxide. A yellow flame isn't something to monitor casually; stop using that burner and have it inspected. And if you ever smell gas, call the National Gas Emergency line on 0800 111 999 first — free, 24/7. Gas appliance checks across Southampton.",
        tags=["#GasSafety", "#GasHob", "#CarbonMonoxide", "#KitchenSafety"],
    ),
    # 50 — p140 cost_reveal: what a dripping tap costs per year
    dict(
        pillar="cost_reveal",
        topic="What one dripping tap costs in a year",
        slug="tap-repair", suffix="dripping-tap",
        hint="asset:tap", itype="asset", banner="lower",
        caption="5,500 litres a year, drip by drip 💧",
        cta="QUOTE", extra_cta=None,
        fb="💧 One drip per second. Sounds like nothing. Adds up to roughly 5,500 litres a year — straight down the plughole.\n\nOn a water meter, you're paying for every one of those litres. If it's the HOT tap, you also paid to heat them first. Add the brown stain ring it etches into the basin, and the valve seat it's slowly chewing up, making the eventual fix bigger.\n\nThe repair is usually a washer or cartridge — minutes of work, small money.\n\nA dripping tap isn't a quirk of the house. It's a standing order you never signed.",
        ig="One drip per second = ~5,500 litres a year 💧\n\nStraight down the plughole.\n\nOn a meter? You're paying for every litre. Hot tap? You paid to HEAT them first. Plus the stain ring it etches into the basin, and the valve seat it slowly chews up — making the eventual fix bigger.\n\nThe repair is usually a washer or cartridge. Minutes of work, small money.\n\nA dripping tap isn't a quirk of the house. It's a standing order you never signed.",
        tw="One drip per second ≈ 5,500 litres a year down the plughole. 💧\n\nOn a meter you pay for every litre — and if it's the hot tap, you heated them too.\n\nA dripping tap is a standing order you never signed.",
        gb="A tap dripping once per second wastes roughly 5,500 litres of water a year — and on a metered supply, you're billed for every litre. If it's the hot tap, the cost doubles up: you've paid to heat that water before sending it down the plughole. There's mechanical cost too. A persistent drip etches a stain ring into the basin and gradually erodes the valve seat, turning what would have been a simple washer or cartridge swap into a larger repair. The fix itself is typically minutes of work and modest money. A dripping tap isn't a harmless quirk — it's a standing order you never agreed to. Tap repairs across Southampton.",
        tags=["#DrippingTap", "#TapRepair", "#WaterBill", "#PlumbingTips"],
    ),
    # 51 — p141 work: shower cartridge job story
    dict(
        pillar="work",
        topic="Job story — the scalding-then-freezing shower in St Denys",
        slug="shower-repair", suffix="shower-cartridge",
        hint="work:shower", itype="work", banner="lower",
        caption="Cartridge swap, shower saved 🚿",
        cta="QUOTE", extra_cta=None,
        fb="🚿 St Denys, last week: a shower that ran scalding, then freezing, then scalding — usually timed perfectly with someone flushing the loo.\n\nThe culprit: the thermostatic cartridge inside the shower valve. Its whole job is holding your set temperature steady when the cold pressure dips. When it wears (and in our hard water, it wears), you get the hot-cold lottery.\n\nCartridge swapped, temperature rock steady, household morale restored.\n\nIf your shower can't hold its temperature when a tap runs elsewhere — that's the part to suspect.",
        ig="The scalding ↔ freezing shower lottery, solved 🚿\n\nSt Denys, last week: shower running scalding, then freezing, then scalding — perfectly timed with every loo flush.\n\nThe culprit: the thermostatic cartridge inside the valve. Its whole job is holding your set temperature when cold pressure dips. In our hard water, it wears — and you get the lottery.\n\nCartridge swapped. Temperature rock steady. Household morale restored.\n\nShower can't hold temp when a tap runs elsewhere? That's the part to suspect.",
        tw="Shower in St Denys: scalding ↔ freezing with every loo flush. 🚿\n\nCulprit: worn thermostatic cartridge — its one job is holding temp steady. Swapped, sorted, morale restored.",
        gb="A job from St Denys last week: a shower running scalding, then freezing, then scalding again — usually timed with a toilet flush or a tap running elsewhere in the house. The culprit was the thermostatic cartridge inside the shower valve. Its entire purpose is to hold your set temperature steady when the cold supply pressure dips, and when it wears — which Southampton's hard water accelerates — you get the hot-and-cold lottery instead. With the cartridge replaced, the temperature held rock steady through every test. If your shower can't maintain its temperature when water runs elsewhere in the house, the thermostatic cartridge is the prime suspect, and it's a same-visit fix in most cases.",
        tags=["#ShowerRepair", "#StDenys", "#HardWater", "#PlumbingRepairs"],
    ),
    # 52 — p142 local: Ocean Village & city centre flats
    dict(
        pillar="local",
        topic="Area coverage — Ocean Village and city centre flats",
        slug="combi-install", suffix="ocean-village",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering Ocean Village 📍",
        cta="QUOTE", extra_cta=None,
        fb="📍 Ocean Village, the waterfront, and the city centre flats — yes, covered.\n\nApartment heating is its own world: compact combis working hard in cupboards, pipework buried in service voids, and management companies with rules about everything from parking to flue positions.\n\n🔧 Combi repairs and replacements sized for apartment life\n📋 Paperwork managing agents actually accept\n🚐 And I know which buildings have the awkward parking — that's half the battle down there\n\nFlat living shouldn't mean second-class heating service.",
        ig="Ocean Village + the city centre flats 📍 Covered.\n\nApartment heating is its own world:\n\n🔧 Compact combis working hard in cupboards\n🧱 Pipework buried in service voids\n📋 Management companies with rules about everything\n\nI do combi repairs and replacements sized for apartment life, with the paperwork managing agents actually accept — and I know which buildings have the nightmare parking. That's half the battle down there. 😄\n\nFlat living shouldn't mean second-class heating service.",
        tw="Ocean Village + city centre flats 📍 Covered — compact combi repairs and replacements, managing-agent-friendly paperwork, and hard-won knowledge of which buildings have nightmare parking. 😄",
        gb="Ocean Village, the waterfront developments and Southampton's city centre flats are all covered. Apartment heating is genuinely its own discipline: compact combi boilers working hard in kitchen cupboards, pipework buried in service voids, flue positions constrained by the building, and management companies with requirements for everything from access to paperwork. I handle combi repairs and full replacements sized correctly for apartment demand, provide the documentation managing agents expect, and — no small thing — have learned which buildings have the awkward parking and access arrangements. Flat living shouldn't mean second-class heating service. Combi installations and repairs across central Southampton.",
        tags=["#OceanVillage", "#SO14", "#ApartmentLiving", "#CombiBoiler"],
    ),
    # 53 — p143 trust: I show up when I say
    dict(
        pillar="trust",
        topic="If I say 2pm, it's 2pm — why punctuality is policy",
        slug="boiler-repair", suffix="on-time",
        hint="brand:wes_portrait", itype="brand", banner="lower",
        caption="If I say 2pm, it's 2pm ⏰",
        cta="QUOTE", extra_cta=None,
        fb="⏰ The worst part of booking a tradesperson isn't the bill. It's the waiting in.\n\nThe 'between 8 and 6' window. The whole day booked off work. The silence when nobody shows.\n\nSo here's my policy, plain and simple:\n✅ You get a time, not a day-long window\n✅ If a job before yours overruns, you get a message with a new honest ETA — not radio silence\n✅ If I'm ever properly stuck, you'll know before your kettle's been on standby for an hour\n\nYour time is worth the same as mine. Treating it that way isn't a perk — it's the baseline.",
        ig="The worst part of booking a trade isn't the bill. It's the waiting in. ⏰\n\nThe 'between 8 and 6' window. The day booked off work. The silence when nobody shows.\n\nMy policy, plain:\n✅ You get a TIME, not a day-long window\n✅ If the job before yours overruns — you get a message with an honest new ETA\n✅ Never radio silence\n\nYour time is worth the same as mine. That's not a perk. It's the baseline.",
        tw="The worst part of booking a trade isn't the bill — it's the waiting in. ⏰\n\nMy policy: you get a time, not a 'between 8 and 6'. If a job overruns, you get a message, not silence. Baseline, not perk.",
        gb="Ask people their worst experience with trades and it's rarely the bill — it's the waiting in. The 'between 8am and 6pm' window, the day booked off work, the silence when nobody arrives. My policy is simple. You get an actual time, not a day-long window. If the job before yours overruns — which honest work sometimes does — you get a message with a realistic new arrival time, not radio silence. And if something genuinely derails the day, you'll know early enough to rescue yours. Punctuality isn't a premium feature; it's basic respect for the fact that your time is worth the same as mine. Boiler repairs and heating work across Southampton.",
        tags=["#OnTime", "#Reliable", "#TrustedTrader", "#CustomerService"],
    ),
    # 54 — p144 personal: proudest fix
    dict(
        pillar="personal",
        topic="My proudest fix — the leak three firms couldn't find",
        slug="central-heating", suffix="proudest-fix",
        hint="brand:wes_with_tools", itype="brand", banner="lower",
        caption="My proudest fix 🔧",
        cta="QUOTE", extra_cta=None,
        fb="🔧 My proudest fix wasn't a complicated one. It was a stubborn one.\n\nA system losing pressure for months. Two firms had already been: 'no leak findable, probably needs a new boiler'. The family were saving up for one.\n\nI went old-school. Isolated the system a section at a time, days apart, watching the gauge each visit. The drop only happened with one zone open — and under that floor, a fitting weeping so slowly it dried before it could stain.\n\nOne small repair. No new boiler. The gauge hasn't moved since.\n\nProudest fixes aren't the cleverest welds. They're the expensive guesses you get to cancel.",
        ig="My proudest fix wasn't clever. It was stubborn. 🔧\n\nA system losing pressure for months. Two firms had said 'no leak findable — probably needs a new boiler'. The family were saving up for one.\n\nOld-school method: isolate one section at a time, days apart, watch the gauge. The drop only came with one zone open — and under that floor, a fitting weeping so slowly it dried before it could stain.\n\nOne small repair. No new boiler. Gauge hasn't moved since.\n\nThe best fixes are the expensive guesses you get to cancel.",
        tw="Proudest fix: a pressure loss two firms called 'new boiler territory'. 🔧\n\nIsolated it zone by zone — found a fitting weeping under one floor. Small repair, no new boiler, gauge steady since.",
        gb="The fix I'm proudest of wasn't technically complicated — it was stubborn. A central heating system had been losing pressure for months. Two firms had visited, found nothing, and suggested the family budget for a new boiler. The methodical route took longer: isolating the system one section at a time across several days and watching the gauge between visits. The pressure only dropped with one zone open, and under that floor was a compression fitting weeping so slowly the water dried before it could leave a stain. One small repair later, the gauge hasn't moved since — and nobody bought a boiler they didn't need. Proper diagnosis pays for itself. Central heating fault-finding across Southampton.",
        tags=["#CentralHeating", "#LeakDetection", "#Diagnostics", "#HonestTrade"],
    ),
    # 55 — p145 cost_reveal: sludge is on your gas bill (heatex pair)
    dict(
        pillar="cost_reveal",
        topic="Clean vs clogged heat exchanger — the gas bill difference",
        slug="power-flush", suffix="clean-vs-clogged",
        hint="asset:heatex", itype="asset", banner="upper",
        caption="Clean vs clogged: same boiler 💷",
        cta="SLUDGE", extra_cta=None,
        fb="💷 Same part. Same boiler model. Wildly different gas bills.\n\nOn the left: a heat exchanger from a system that's serviced yearly with a filter fitted. On the right: one from a system that's never been flushed.\n\nThat black coating is sludge and combustion debris baked onto the metal — and it works like a blanket between the flame and your water. The clogged one burns MORE gas to deliver LESS heat, every hour it runs.\n\nThis is why flushing and filters aren't upsells. They're the difference between these two photos.",
        ig="Same part. Same boiler. Wildly different gas bills. 💷\n\nLeft: heat exchanger from a system serviced yearly, filter fitted.\nRight: one that's never been flushed.\n\nThat black coating is sludge baked onto the metal — a blanket between the flame and your water. The clogged one burns MORE gas for LESS heat. Every single hour it runs.\n\nFlushing and filters aren't upsells. They're the difference between these two photos.",
        tw="Two heat exchangers, same boiler model. One serviced + filtered, one never flushed. 💷\n\nThat black coating is a blanket between flame and water — more gas burned, less heat delivered, every hour.",
        gb="One photo, two stories. Both of these heat exchangers came from the same model of boiler. The clean one lived in a system that gets a yearly service with a magnetic filter fitted; the black one came from a system that had never been flushed. That dark coating is iron sludge and debris baked onto the metal, and it behaves like a blanket between the flame and your water — so the boiler burns more gas to deliver less heat, every hour it runs, while the components work harder and fail sooner. This is why power flushing and filters aren't upsells: they're the difference between these two photographs. Power flushing across Southampton.",
        tags=["#PowerFlush", "#HeatExchanger", "#GasBill", "#BoilerCare"],
    ),
    # 56 — p146 emergency: water through the ceiling first moves
    dict(
        pillar="emergency",
        topic="Water coming through the ceiling — the first five moves",
        slug="pipe-leak", suffix="ceiling-leak",
        hint="work:pipe_repair", itype="work", banner="upper",
        caption="Water through the ceiling? Do this 🚨",
        cta=None, extra_cta="Save this. You'll think clearer with a checklist.",
        fb="🚨 Water coming through the ceiling. Heart pounding. Here's the order that saves your house:\n\n1️⃣ Stopcock OFF — usually under the kitchen sink. (Heating leak? Boiler off too.)\n2️⃣ Kill the lights and electrics in that room at the consumer unit — water and wiring don't negotiate\n3️⃣ Bucket under the drip. If the ceiling is bulging, pierce the bulge with a screwdriver and let it drain INTO the bucket — controlled drip beats collapsed ceiling\n4️⃣ Photos of everything for insurance\n5️⃣ THEN ring a plumber\n\nSave this. You'll think clearer with a checklist than with adrenaline.",
        ig="Water through the ceiling. Heart pounding. Do THIS: 🚨\n\n1️⃣ Stopcock OFF (usually under the kitchen sink). Heating leak? Boiler off too\n2️⃣ Lights + electrics OFF in that room at the consumer unit\n3️⃣ Bucket under the drip — and if the ceiling is BULGING, pierce the bulge and drain it into the bucket. A controlled drip beats a collapsed ceiling\n4️⃣ Photos of everything for insurance\n5️⃣ THEN ring a plumber\n\nChecklists beat adrenaline. Save this one.",
        tw="Water through the ceiling? 🚨\n\n1. Stopcock OFF\n2. That room's electrics OFF\n3. Bulging ceiling? Pierce + drain into a bucket — beats a collapse\n4. Photos for insurance\n5. THEN ring a plumber",
        gb="Water coming through a ceiling is one of the most stressful moments a home can produce, and the right order of actions makes a real difference. First, turn the stopcock off — usually under the kitchen sink — and if the leak is from a heating pipe, switch the boiler off too. Second, isolate the lights and electrics in the affected room at the consumer unit. Third, get a bucket under the drip; if the ceiling is bulging, pierce the bulge and drain it in a controlled way — far better than letting the plasterboard collapse. Photograph everything for your insurer, and then call a plumber. Emergency leak repairs across Southampton.",
        tags=["#PipeLeak", "#WaterLeak", "#EmergencyTips", "#HomeInsurance"],
    ),
    # 57 — p147 tips: condensate pipe freezing prevention
    dict(
        pillar="tips",
        topic="Lag the condensate pipe now — beat the first frost",
        slug="boiler-repair", suffix="lag-condensate",
        hint="ai", itype="ai", banner="upper",
        caption="Lag this pipe. Beat the frost ❄️",
        cta=None, extra_cta="Save this — future-you, mid-cold-snap, says thanks.",
        fb="❄️ There's a white plastic pipe running from your boiler to an outside drain. It's the single most common reason boilers die on the first frosty morning of winter — and protecting it costs a few quid.\n\nDo this before the cold snap, not during:\n✅ Lag the outside run with waterproof foam insulation — outdoor-rated, not the indoor grey stuff\n✅ Check the pipe falls steeply with no sags where water can pool and freeze\n✅ Long, skinny outside run? Worth asking about rerouting or upsizing it\n\nTen minutes with a roll of lagging in October saves a freezing morning queue in January.",
        ig="This pipe kills more boilers in January than any other part ❄️\n\nThe white plastic one running outside from your boiler — the condensate pipe. First hard frost, it freezes, boiler locks out.\n\nProtect it NOW, not mid-cold-snap:\n✅ Waterproof outdoor-rated foam lagging on the outside run\n✅ Check it falls steeply — no sags where water pools and freezes\n✅ Long skinny outside run? Ask about rerouting or upsizing\n\nTen minutes in October saves the freezing January queue.",
        tw="The white pipe outside your boiler kills more of them in January than any other part. ❄️\n\nLag it with outdoor-rated foam now; check for sags where water pools. Ten minutes well spent.",
        gb="Of all winter boiler failures, one of the most common — and most preventable — is the frozen condensate pipe: the white plastic pipe carrying slightly acidic water from your boiler to an outside drain. When it freezes, the boiler shuts down on the coldest morning of the year, along with thousands of others. Prevention is cheap and quick: lag the external run with waterproof, outdoor-rated foam insulation; check the pipe falls steeply with no sags where water can pool and freeze; and if you have a long, narrow external run, consider having it upsized or rerouted internally. Ten minutes in autumn beats a freezing queue in January. Boiler work across Southampton.",
        tags=["#BoilerTips", "#WinterPrep", "#CondensatePipe", "#HeatingTips"],
        prompt="SCENE: a UK house exterior brick wall in crisp autumn light, photorealistic, slight low angle.\nSUBJECT: a white plastic condensate pipe running down the brick wall to a gully drain, neatly wrapped in black waterproof foam lagging, a roll of spare lagging resting on the ground beside it. Text on a clean navy banner across the upper third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Lag this pipe. Beat the frost ❄️\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; warm brick and autumn palette, no people, no brand logos.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos. Photorealistic, not illustrative. One pipe only, no extra pipes or fittings.",
    ),
    # 58 — p148 work: toilet flush mechanism job
    dict(
        pillar="work",
        topic="Job story — the phantom-filling toilet in Millbrook",
        slug="toilet-repair", suffix="toilet-flush",
        hint="work:toilet_repair", itype="work", banner="lower",
        caption="One worn part, one happy loo 🚽",
        cta="QUOTE", extra_cta=None,
        fb="🚽 Millbrook, this week: a toilet that kept refilling itself every twenty minutes, day and night. The household had tuned the hiss out months ago.\n\nThat hiss was the flush valve seal — worn out, letting water trickle from cistern to pan around the clock. On a meter, that's paid-for water going literally down the toilet, 24/7.\n\nOne worn seal swapped, cistern holding tight, hiss gone.\n\n💡 Quick test for your own loo: a sheet of toilet paper on the back of the pan. If it darkens between flushes, your cistern is leaking too.",
        ig="That toilet hiss you've tuned out? It's money. 🚽\n\nMillbrook this week: a loo refilling itself every 20 minutes, day and night. The household stopped hearing it months ago.\n\nCause: a worn flush valve seal, trickling water from cistern to pan around the clock. On a meter, that's paid-for water going literally down the toilet. 24/7.\n\nOne seal swapped. Cistern holding. Hiss gone.\n\n💡 Test yours: lay toilet paper on the back of the pan. Darkens between flushes = your cistern leaks too.",
        tw="A loo in Millbrook kept refilling every 20 mins — a worn flush seal trickling water to the pan 24/7. On a meter, that's money down the toilet. Literally. 🚽\n\nOne seal swapped, sorted.",
        gb="A small job in Millbrook this week with a lesson for every household: a toilet that refilled itself every twenty minutes, day and night. The family had tuned out the hiss months ago — but that hiss was a worn flush valve seal letting water trickle continuously from cistern to pan. On a metered supply, that's paid-for water running down the toilet around the clock. One replacement seal later, the cistern holds tight and the phantom refills have stopped. A quick test for your own bathroom: lay a sheet of toilet paper across the back of the pan; if it darkens between flushes, your cistern is leaking too. Toilet repairs across Southampton.",
        tags=["#ToiletRepair", "#Millbrook", "#WaterBill", "#PlumbingRepairs"],
    ),
    # 59 — p149 trust: the no-pressure quote promise
    dict(
        pillar="trust",
        topic="My no-pressure quote promise",
        slug="new-boiler", suffix="no-pressure-quote",
        hint="ai", itype="ai", banner="lower",
        caption="A quote, not a sales pitch 📋",
        cta="QUOTE", extra_cta=None,
        fb="📋 My quote promise, in plain English:\n\n✅ I'll tell you what I'd do if it were my own house — including 'repair it, it's got years left' when that's the truth\n✅ The number you get is the number. Written down, itemised, no decoding required\n✅ No 'this price is only valid if you sign today' theatre\n✅ And if you never ring back? No chasing calls, no hard feelings. It's your boiler and your money.\n\nA quote should give you information, not pressure. That's the whole promise.",
        ig="A quote should give you information. Not pressure. 📋\n\nMy promise, plain:\n\n✅ I'll tell you what I'd do in my OWN house — including 'repair it, it's got years left' when that's true\n✅ The number you get is the number. Written, itemised\n✅ Zero 'only valid if you sign today' theatre\n✅ Never ring back? No chasing calls. No hard feelings\n\nIt's your boiler and your money. The quote is just the information you need to decide.",
        tw="My quote promise: what I'd do in my own house (including 'repair it'), a written itemised number, no sign-today theatre, and no chasing calls if you go quiet. 📋\n\nInformation, not pressure.",
        gb="Getting a quote shouldn't feel like being worked on by a salesperson, so here's the standing promise. You'll get my honest recommendation — the same thing I'd do in my own house, which regularly means 'repair it, it has years left' rather than a replacement pitch. The price arrives written and itemised, with no decoding required and no 'only valid if you sign today' theatre. And if you take the quote and never ring back, that's completely fine: no chasing calls, no awkwardness. It's your home and your money; a quote is simply the information you need to make a good decision. New boiler quotes across Southampton.",
        tags=["#HonestQuote", "#NewBoiler", "#NoPressure", "#HonestTrade"],
        prompt="SCENE: a warm UK kitchen table in soft window light, photorealistic, top-down three-quarter view.\nSUBJECT: a single neatly printed quotation document on a clipboard, itemised lines visible but unreadable, a pen resting beside it and a mug of tea nearby. Text on a clean navy banner across the lower third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"A quote, not a sales pitch 📋\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; warm honest domestic palette, no people, no readable small text on the document, no brand logos.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render the banner text verbatim, no extra words, no duplicate lines, no fake logos. The document's body text must be soft-focus and unreadable. Photorealistic, not illustrative.",
    ),
    # 60 — p150 personal: what customers teach me
    dict(
        pillar="personal",
        topic="What ten years of customers have taught me",
        slug="plumbing", suffix="customer-lessons",
        hint="brand:wes_portrait", itype="brand", banner="lower",
        caption="What customers taught me 🏠",
        cta=None, extra_cta="Tag someone who always puts the kettle on for the trades.",
        fb="🏠 Ten years of being welcomed into Southampton's kitchens teaches you things no course covers. What customers taught me:\n\n☕ Nobody actually wants 'the cheapest plumber'. They want to stop worrying about the thing\n🗣️ If I can't explain the fault without jargon, I don't understand it well enough yet\n👢 How you leave a kitchen matters as much as what you fixed in it\n🤝 Trust isn't won in the quote. It's won in the small stuff — shoes off, dust sheets down, texts answered\n\nThanks for having me in your homes, Southampton. The education continues.",
        ig="Ten years of Southampton kitchens. Here's what customers taught ME: 🏠\n\n☕ Nobody really wants 'the cheapest plumber' — they want to stop worrying about the thing\n🗣️ If I can't explain a fault without jargon, I don't understand it well enough yet\n👢 How you leave a kitchen matters as much as what you fixed in it\n🤝 Trust isn't won in the quote — it's won in the small stuff. Shoes off. Dust sheets down. Messages answered\n\nThanks for having me in your homes, Southampton. The education continues.",
        tw="10 years of customers taught me: nobody wants the cheapest plumber — they want to stop worrying. And trust isn't won in the quote; it's won in dust sheets, clean boots and answered messages. 🏠",
        gb="After ten years of being welcomed into Southampton's homes, the biggest lessons haven't come from boilers — they've come from customers. People don't actually want 'the cheapest plumber'; they want to stop worrying about the thing that's broken. If a fault can't be explained without jargon, it isn't understood well enough yet. How you leave a kitchen — dust sheets, clean boots, everything wiped down — matters as much as what was fixed in it. And trust is rarely won in the quote; it's won in small, repeated courtesies. Thank you to every household that's had me through the door. The education continues. Plumbing and heating across Southampton.",
        tags=["#ThankYou", "#LocalBusiness", "#Southampton", "#TradesLife"],
    ),
]
