# Posts 1-20 of the 60-post batch (p091-p110). Content only; composition in build_60_batch.py
# Fields: pillar, topic, slug (short-link), suffix, hint, itype, caption,
#         cta ('QUOTE'|'SERVICE'|'SLUDGE'|None), extra_cta (str|None),
#         fb, ig, tw, gb (bodies WITHOUT links/phone), tags (topic hashtags),
#         banner ('upper'|'lower'), prompt (None=auto overlay, or explicit string), prerendered (optional)

POSTS_A = [
    # 1 — p091 cost_reveal: cost of ignoring a small leak
    dict(
        pillar="cost_reveal",
        topic="What ignoring a small leak actually costs",
        slug="pipe-leak", suffix="small-leak-cost",
        hint="asset:pipe", itype="asset", banner="lower",
        caption="What a 'small' leak really costs 💷",
        cta="QUOTE", extra_cta=None,
        fb="💧 That 'tiny' drip under the sink is one of the most expensive small jobs in the house — if you leave it.\n\nWhat it quietly eats through:\n🪵 The cabinet base — swollen and rotten within months\n🧱 Plaster, skirting and the ceiling below\n🦠 Mould treatment once the damp sets in\n💷 Hundreds in making-good, for a fix that takes me under an hour\n\nA drip never fixes itself. It just gets a bigger audience.",
        ig="The most expensive drip in Southampton 💧\n\nA 'tiny' leak under the sink doesn't stay tiny. It soaks the cabinet base, creeps into the floor, then shows up as a stain on the ceiling below.\n\nBy then you're paying for joinery and decorating — not just plumbing.\n\nThe actual fix? Usually a worn washer or loose fitting. Under an hour, clear price agreed first.\n\nIf you've spotted a drip or a musty smell under a sink, don't give it a head start.",
        tw="That 'tiny' drip under the sink? It quietly rots the cabinet, the floor and the ceiling below. The fix takes under an hour. The damage takes months to show. 💧",
        gb="A slow leak under a sink rarely looks urgent — but it's one of the most expensive small problems a home can have. Water wicks into the cabinet base, then the floor, then the plasterboard below, and by the time the damage is visible you're paying for joinery and decorating as well as the plumbing. The repair itself is usually quick: a worn washer, a loose compression fitting or a failed trap, sorted in under an hour with a clear price agreed up front. If you've noticed a drip, dampness or a musty smell under a sink anywhere in Southampton, it's worth getting it looked at before it spreads.",
        tags=["#PipeLeak", "#LeakRepair", "#WaterDamage", "#HomeMaintenance"],
    ),
    # 2 — p092 tips: what boiler pressure should read
    dict(
        pillar="tips",
        topic="What your boiler pressure gauge should actually read",
        slug="boiler-repair", suffix="boiler-pressure",
        hint="asset:boiler", itype="asset", banner="upper",
        caption="Boiler pressure: what's normal? 📊",
        cta="QUOTE", extra_cta="Save this for when you need it.",
        fb="📊 Your boiler's pressure gauge — what should it actually say?\n\n✅ 1 to 1.5 bar when the system is cold\n🔥 Up to around 2 bar while the heating is running\n⚠️ Below 1 bar — heating struggles, boiler may lock out\n🚨 Above 2.5 bar — too high, often an overfilled system or a tired expansion vessel\n\nTopping up now and then is normal. Topping up every week isn't — that's a leak or a part on its way out, and it's worth catching before winter.",
        ig="The dial on your boiler, decoded 📊\n\nMost people only look at it when the heating stops. Here's what it should read:\n\n✅ 1–1.5 bar cold\n🔥 Around 2 bar when running\n⚠️ Under 1 bar — expect lockouts\n🚨 Over 2.5 bar — too high, needs a look\n\nTopping up once a season? Normal.\nTopping up every week? That's a slow leak or a tired part — get it checked before it picks the coldest day to quit.",
        tw="Boiler pressure, decoded 📊\n\n✅ 1–1.5 bar cold\n🔥 ~2 bar running\n⚠️ Under 1 = lockouts\n🚨 Over 2.5 = too high\n\nTopping up every week? That's a leak talking.",
        gb="Your boiler's pressure gauge tells you more than most people realise. When the system is cold it should sit between 1 and 1.5 bar, rising to around 2 bar with the heating running. Below 1 bar the boiler may lock out; above 2.5 bar usually points to an overfilled system or a failing expansion vessel. The key sign to act on is repetition: topping the pressure up once a season is normal, but doing it every week means water is escaping somewhere — a small leak or a part on its way out. Catching that early is a far cheaper job than a mid-winter breakdown. Serving Southampton and surrounding areas.",
        tags=["#BoilerTips", "#BoilerPressure", "#BoilerRepair", "#HomeTips"],
    ),
    # 3 — p093 local: Woolston
    dict(
        pillar="local",
        topic="Area coverage — Woolston",
        slug="boiler-repair", suffix="woolston",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering Woolston 📍",
        cta="QUOTE", extra_cta=None,
        fb="📍 Woolston — you're covered.\n\nFrom the older terraces off Victoria Road to the newer builds at Centenary Quay, I'm across the Itchen more weeks than not.\n\n🔧 Boiler repairs with a £100 diagnostic — most minor fixes done on the spot\n🔥 Servicing, radiators and general plumbing\n🚐 One van, one name, no call centre\n\nIf your heating's playing up on the east side of the river, you don't need to wait for a firm to 'get someone out to you'.",
        ig="Woolston, you're covered 📍\n\nFrom the terraces off Victoria Road to the new flats at Centenary Quay — I'm over the Itchen most weeks.\n\n🔧 Boiler repairs (£100 diagnostic, most minor fixes done on the spot)\n🔥 Servicing, radiators, general plumbing\n🚐 One van, one name, no call centre\n\nHeating playing up on the east side of the river? You know who to call.",
        tw="Woolston 📍 You're covered — boiler repairs, servicing and plumbing from a local one-man band. £100 diagnostic, most minor fixes done on the spot.",
        gb="Woolston homeowners — Better Call Wes covers your side of the Itchen. From the established terraces around Victoria Road to the newer developments at Centenary Quay, I handle boiler repairs, annual servicing, radiator work and general plumbing across the area. Repairs start with a £100 diagnostic that includes most minor fixes on the spot, and you'll always get a clear written price before any parts are ordered. As a sole trader you deal with one person from first message to finished job — no call centre, no 'we'll get someone out to you'. Gas Safe registered and based locally in Southampton.",
        tags=["#Woolston", "#SO19", "#BoilerRepair", "#LocalTrades"],
    ),
    # 4 — p094 personal: the tool I can't work without
    dict(
        pillar="personal",
        topic="The tool I can't work without",
        slug="plumbing", suffix="favourite-tool",
        hint="brand:wes_with_tools", itype="brand", banner="lower",
        caption="The tool I can't work without 🔧",
        cta=None, extra_cta="Boiler acting up? Send me a WhatsApp video on 07700 155 655.",
        fb="🔧 People always expect me to name something fancy. Honestly? It's my multimeter.\n\nHalf of modern heating work is electrical — sensors, thermistors, PCBs, pumps. The multimeter is the difference between guessing which part has failed and *knowing*.\n\nGuessing costs you money: parts you didn't need, second visits, 'let's try this'. Measuring costs ten minutes.\n\nIt's not shiny. It's not expensive. But it's the first thing I check is in the van every morning.",
        ig="The tool I genuinely can't work without 🔧\n\nNot the pipe bender. Not the press gun. My multimeter.\n\nHalf of modern heating work is electrical — sensors, thermistors, pumps, PCBs. The multimeter is the difference between guessing which part failed and knowing.\n\nGuessing costs you money: parts you didn't need, second visits, 'let's try this and see'.\n\nMeasuring costs ten minutes.\n\nWhat's the one tool you couldn't do your job without? 👇",
        tw="The tool I can't work without isn't fancy — it's my multimeter. 🔧\n\nIt's the difference between guessing which part failed and knowing. Guessing costs you money. Measuring costs ten minutes.",
        gb="Ask most people what a heating engineer's most important tool is and they'll guess a wrench. For me it's the multimeter. So much of modern boiler work is electrical — thermistors, sensors, pumps, control boards — and accurate measurement is the difference between diagnosing a fault and guessing at one. Guesswork is how customers end up paying for parts they didn't need and waiting for second visits. Measurement means the right part, fitted once. It's the first thing I check is in the van every morning before heading out across Southampton.",
        tags=["#HeatingEngineerLife", "#ToolsOfTheTrade", "#BoilerRepair", "#TradesLife"],
    ),
    # 5 — p095 work: sludge reveal job story
    dict(
        pillar="work",
        topic="Job story — what came out of a Bitterne heating system",
        slug="power-flush", suffix="sludge-reveal",
        hint="work:powerflush", itype="work", banner="upper",
        caption="This came out of a radiator 🤢",
        cta="SLUDGE", extra_cta=None,
        fb="🤢 This came out of a three-bed in Bitterne last week.\n\nThe symptoms: radiators cold at the bottom, boiler working overtime, bills creeping up every winter. The cause: years of black iron sludge sitting in the system, strangling the flow.\n\nA power flush pushed it all out — that water started the day clear. By the end the rads were hot top to bottom for the first time in years.\n\nIf your radiators have cold patches, this is probably what's inside them.",
        ig="This came out of someone's radiators 🤢\n\nThree-bed in Bitterne. Rads cold at the bottom, bills creeping up, boiler working overtime.\n\nThe cause? Years of black iron sludge sitting in the pipework, strangling the flow.\n\nA power flush pushed all of this out — and the rads ran hot top to bottom for the first time in years.\n\nCold patches on your radiators? This is probably what's inside them.",
        tw="This came out of a heating system in Bitterne 🤢\n\nRads cold at the bottom + rising bills = years of black sludge strangling the flow. A power flush sorted it in a day.",
        gb="A recent job in Bitterne shows what's hiding inside many Southampton heating systems. The radiators were cold at the bottom, the boiler was working harder every winter, and bills kept creeping up. The cause was years of accumulated black iron oxide sludge restricting flow through the pipework and radiators. A full power flush cleared the system — the flush water ran jet black before finally running clear — and the radiators heated evenly from top to bottom again. If your radiators have cold patches or your system takes ages to warm up, sludge is the most likely culprit, and flushing it out protects both your boiler and your gas bill.",
        tags=["#PowerFlush", "#CentralHeating", "#Bitterne", "#RadiatorProblems", "#BoilerCare"],
    ),
    # 6 — p096 cost_reveal: winter emergency premium vs autumn service
    dict(
        pillar="cost_reveal",
        topic="September service vs January breakdown — the real maths",
        slug="boiler-service", suffix="winter-premium",
        hint="ai", itype="ai", banner="lower",
        caption="September service or January breakdown? 🗓️",
        cta="SERVICE", extra_cta=None,
        fb="🗓️ Every January it's the same story across the trade: breakdown season.\n\nDiaries full. Parts in demand. Families queuing for callouts in the coldest week of the year — paying breakdown money for problems a service would have caught in September.\n\nAn autumn service finds the tired parts while it's still warm out:\n✅ Weak expansion vessel\n✅ Scaled heat exchanger\n✅ Sticky diverter valve\n\nThe cheapest boiler repair is the one that never happens.",
        ig="September service or January breakdown? 🗓️\n\nEvery winter, the same pattern: the coldest week arrives and the breakdown calls flood in — most of them preventable.\n\nAn autumn service catches the tired parts while it's still warm:\n\n✅ Weak expansion vessel\n✅ Scaled heat exchanger\n✅ Sticky diverter valve\n\nWaiting for the breakdown means queuing in peak season, with the family cold while parts arrive.\n\nThe cheapest repair is the one that never happens.",
        tw="January breakdown vs September service 🗓️\n\nOne means queuing for parts in the coldest week of the year. The other catches the tired parts early. The cheapest repair is the one that never happens.",
        gb="There's a clear pattern in heating: the coldest week of the year is also the busiest for breakdowns, and most of those failures were predictable. A weak expansion vessel, a scaled heat exchanger or a sticky diverter valve will all show themselves during a proper annual service — months before they leave a family without heating in January, queuing for parts in peak season. Booking a service in late summer or autumn means any worn components are found and dealt with calmly, on your schedule, rather than as an emergency. If your boiler hasn't been serviced in the last twelve months, now is the sensible time to book it in.",
        tags=["#BoilerService", "#BoilerTips", "#WinterReady", "#HomeMaintenance"],
        prompt="SCENE: a warm UK kitchen worktop in soft morning light, shallow depth of field, photorealistic.\nSUBJECT: a wall calendar open to September propped beside a mug of tea and a boiler service reminder note. Text on a clean navy banner across the lower third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"September service or January breakdown? 🗓️\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; warm domestic palette, no people, no brand logos.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos. Photorealistic, not illustrative.",
    ),
    # 7 — p097 emergency: what counts as a gas emergency
    dict(
        pillar="emergency",
        topic="What counts as a gas emergency — and who to call first",
        slug="gas-leak", suffix="gas-emergency",
        hint="work:gas_inspection", itype="work", banner="upper",
        caption="Smell gas? Do this first ⚠️",
        cta=None, extra_cta="Save this — and share it with someone who'd panic.",
        fb="⚠️ Smell gas? Here's the order to do things in — it matters.\n\n1️⃣ Don't flick any switches — on OR off\n2️⃣ Open doors and windows\n3️⃣ Turn the gas off at the meter if you can reach it safely\n4️⃣ Call the National Gas Emergency line: 0800 111 999 — free, 24/7. They make it safe.\n5️⃣ THEN call a Gas Safe engineer to find and fix the fault\n\nThe emergency line makes it safe. The engineer makes it right. Different jobs — know both numbers.",
        ig="Smell gas? Do this — in this order ⚠️\n\n1️⃣ Don't touch any switches — on OR off\n2️⃣ Open doors and windows\n3️⃣ Turn off the gas at the meter if it's safe to reach\n4️⃣ Call the National Gas Emergency line: 0800 111 999 (free, 24/7) — they make it safe\n5️⃣ THEN a Gas Safe engineer finds and fixes the fault\n\nThe emergency line makes it safe. The engineer makes it right. Two different jobs — save both numbers.",
        tw="Smell gas? ⚠️\n\n1. No switches — on or off\n2. Open windows\n3. Gas off at the meter\n4. Call 0800 111 999 (free, 24/7) — they make it safe\n5. Then a Gas Safe engineer fixes the fault",
        gb="If you ever smell gas at home, the order you act in matters. Avoid touching any electrical switches — turning things on or off can create a spark. Open doors and windows, and turn the gas off at the meter if you can reach it safely. Then call the National Gas Emergency line on 0800 111 999 — it's free and staffed 24/7, and their job is to make the property safe. Once it's safe, a Gas Safe registered engineer traces and repairs the actual fault, tests the system and gets you running again. I provide gas leak detection and repair across Southampton.",
        tags=["#GasSafety", "#GasLeak", "#HomeSafety", "#EmergencyTips"],
    ),
    # 8 — p098 tips: summer boiler care
    dict(
        pillar="tips",
        topic="Three summer jobs that prevent winter boiler problems",
        slug="boiler-service", suffix="summer-boiler-care",
        hint="asset:boiler", itype="asset", banner="lower",
        caption="3 summer jobs for your boiler ☀️",
        cta="SERVICE", extra_cta=None,
        fb="☀️ Your boiler barely works in summer — which is exactly when problems sneak up on it.\n\nThree ten-minute jobs that prevent a cold October surprise:\n\n1️⃣ Run the heating for 10–15 minutes once a month. It keeps the pump and valves moving instead of seizing.\n2️⃣ Glance at the pressure gauge — 1 to 1.5 bar cold is healthy.\n3️⃣ Book the service now, in the quiet season, instead of joining the autumn rush.\n\nBoilers don't fail in summer. They fail on the first cold morning you actually need them.",
        ig="Your boiler is quietly seizing up this summer ☀️\n\nMonths of sitting idle is how pumps stick and valves jam — and you find out on the first cold morning of October.\n\nThree ten-minute jobs that prevent it:\n\n1️⃣ Run the heating 10–15 mins once a month — keeps pump and valves moving\n2️⃣ Check the pressure gauge: 1–1.5 bar cold is healthy\n3️⃣ Book the annual service in the quiet season, not the autumn rush\n\nBoilers don't fail in summer. They fail the first morning you need them.",
        tw="Boilers don't fail in summer — they fail the first cold morning you need them. ☀️\n\nPrevention: run the heating 10 mins monthly, check pressure sits at 1–1.5 bar, service it in the quiet season.",
        gb="Summer is when boiler problems quietly develop. Months of sitting idle is how circulation pumps stick and motorised valves seize — and the failure only shows itself on the first cold morning of autumn, right as every heating engineer's diary fills up. Three simple habits prevent it: run your heating for ten to fifteen minutes once a month to keep the moving parts moving, glance at the pressure gauge occasionally (1 to 1.5 bar cold is healthy), and book your annual service during the quiet season rather than the October rush. A summer service means any worn parts are found and sorted long before you depend on the system daily. Covering all of Southampton.",
        tags=["#BoilerService", "#SummerTips", "#BoilerCare", "#HeatingTips"],
    ),
    # 9 — p099 local mascot: the Bargate
    dict(
        pillar="local",
        topic="Where's Wes today? — The Bargate",
        slug="boiler-repair", suffix="wes-bargate",
        hint="asset:logo_mascot", itype="asset", banner="lower",
        caption="Where's Wes today? 📍 The Bargate",
        cta=None, extra_cta="Where should the little fella pop up next? Drop your suggestions below 👇",
        fb="📍 Where's Wes today? Spotted at the Bargate!\n\n800 years guarding Southampton's high street — and not a single recorded service. Don't take maintenance tips from medieval stonework. 😄\n\nLittle Wes is touring the city this summer, one landmark at a time. First stop: the most famous gateway in Hampshire.\n\nWherever you are inside the old walls or way beyond them, the real Wes covers the lot — boilers, heating and plumbing across Southampton.",
        ig="Where's Wes today? 📍\n\nFirst stop on the tour: the Bargate!\n\n800 years guarding the high street and not one recorded service 😄 Don't take maintenance advice from medieval stonework.\n\nLittle Wes is visiting Southampton landmarks all summer — and the real one covers every postcode in between, fixing boilers and plumbing along the way.\n\nGuess where he should pop up next 👇",
        tw="Where's Wes today? 📍 The Bargate — 800 years on guard, zero recorded services. 😄\n\nDon't be like the Bargate. The real Wes covers all of Southampton.",
        gb="A bit of local fun: the Better Call Wes mascot is touring Southampton's landmarks this summer, starting with the Bargate — 800 years guarding the high street and, as far as anyone knows, not a single recorded service. The real work is rather less medieval: boiler repairs, annual servicing, central heating and plumbing across every Southampton postcode, from the old town walls out to the suburbs. One local engineer, clear pricing, and a £100 diagnostic on repairs that covers most minor fixes on the spot. Follow along to see where the little fella turns up next.",
        tags=["#Southampton", "#Bargate", "#LocalBusiness", "#SouthamptonLife", "#WheresWes"],
        prompt="TASK: Place the cartoon mascot character from the source image into a new scene.\n\nSOURCE: The input image is the Better Call Wes logo featuring a cartoon mascot of a Black African plumber in a navy polo holding a wrench and phone. Preserve the mascot's exact appearance, style, colours, and proportions.\n\nSCENE: A photorealistic view of the medieval Bargate in Southampton city centre — the grey stone gatehouse with battlements, arched central passage and clock, shoppers softly blurred on the pedestrianised street, bright daylight — with the cartoon mascot standing playfully in the foreground giving a thumbs up — deliberate cartoon-on-photo contrast, like a mascot sticker on a postcard.\n\nCHANGE: Add ONE caption banner in the lower third.\n- Banner style: solid rectangle, brand navy #0A2540, 88% opacity, full-width, 14% of image height, clean edges\n- Small orange #FF6B00 accent bar, 4px, along the top edge of the banner\n- Headline (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Where's Wes today? 📍 The Bargate\"\n- Typography: bold sans-serif, white, centred, generous kerning, optically sized for social-feed legibility\n\nCONSTRAINTS: Render the headline verbatim. No other text anywhere in the image. Keep the mascot's identity, colours and proportions exactly as in the source. No watermark. No extra logos.\n\nUSE CASE: Instagram social post, square 1:1, 1080x1080.",
    ),
    # 10 — p100 trust: review card #1
    dict(
        pillar="trust",
        topic="Real customer review — Peter's power flush",
        slug="boiler-repair", suffix="real-review",
        hint="review_card", itype="review_card", banner="lower",
        caption="Real review ⭐",
        cta=None, extra_cta=None,
        prerendered="review_cards/review-00-peter.png",
        fb="⭐⭐⭐⭐⭐ \"Good communication, quick response and quick appointment. Turned up on time, job done, no fuss. Exactly how it should be — highly recommended, and that doesn't come easily from me.\"\n\nThat's Peter, after a central heating power flush.\n\nFor a one-man business, a review like this is worth more than any advert. Thank you to everyone who takes a minute to leave one — it genuinely keeps the wheels turning.\n\nNeed a hand with your boiler or heating?",
        ig="\"No fuss. Exactly how it should be.\" ⭐\n\nThat's from Peter, after a central heating power flush:\n\n\"Good communication, quick response and quick appointment. Turned up on time, job done, no fuss. Highly recommended — and that doesn't come easily from me.\"\n\nFor a one-man business, words like that are worth more than any advert. Thank you to everyone who takes a minute to leave a review — it genuinely keeps the wheels turning. 🙏",
        tw="\"Turned up on time, job done, no fuss. Exactly how it should be.\" ⭐⭐⭐⭐⭐\n\nThank you Peter. Reviews like this keep a one-man band going. 🙏",
        gb="\"Good communication, quick response and quick appointment. Turned up on time, job done, no fuss. Exactly how it should be — highly recommended, and that doesn't come easily from me.\" That's a recent five-star review from Peter, following a central heating power flush. As a sole trader, feedback like this means a great deal — there's no marketing department here, just word of mouth from Southampton customers who were happy with the work. Thank you to everyone who has taken the time to leave a review. If your boiler or heating needs attention, I'd be glad to help.",
        tags=["#CustomerReview", "#FiveStars", "#PowerFlush", "#Testimonial"],
        prompt="",
    ),
    # 11 — p101 cost_reveal: what a magnetic filter saves over 5 years
    dict(
        pillar="cost_reveal",
        topic="What a magnetic filter saves you over five years",
        slug="central-heating", suffix="magnetic-filter",
        hint="work:manifold", itype="work", banner="upper",
        caption="What a magnetic filter saves you 🧲",
        cta="SLUDGE", extra_cta=None,
        fb="🧲 The little black canister on your heating pipes might be the best money you never knew you spent.\n\nA magnetic filter catches the black iron sludge BEFORE it reaches your boiler. Over five years, that means:\n\n✅ Fewer breakdowns — sludge is behind a huge share of pump and heat exchanger failures\n✅ A system that stays efficient instead of slowly clogging\n✅ Many boiler warranties kept happy — some makers expect one fitted\n✅ Cheaper services — emptying a filter beats flushing a blocked system\n\nNo filter on your pipework? Worth fixing before the sludge wins.",
        ig="The best £-for-£ part on your heating system 🧲\n\nThat black canister on the pipework near the boiler is a magnetic filter — and over five years it quietly earns its keep:\n\n✅ Catches black iron sludge before it reaches the boiler\n✅ Fewer pump and heat exchanger failures\n✅ System stays efficient instead of slowly clogging\n✅ Keeps many boiler warranties happy\n\nNo filter on your system? That's the cheapest insurance your boiler isn't getting.",
        tw="The black canister on your heating pipes is a magnetic filter 🧲 It catches sludge before it kills your pump or heat exchanger. Five years of protection from one small part. No filter? Worth fixing.",
        gb="A magnetic filter is a small canister fitted to your heating return pipe, and over five years it's one of the best-value parts on the whole system. It catches the black iron oxide sludge that circulating water picks up from radiators — the same sludge responsible for a large share of pump failures, blocked heat exchangers and cold-spotted radiators. With a filter in place the debris is captured and emptied at each annual service, the system stays efficient, and many boiler manufacturers look more kindly on warranty claims. If your Southampton home doesn't have one fitted, it can usually be added in a single visit.",
        tags=["#CentralHeating", "#MagneticFilter", "#BoilerCare", "#HeatingTips"],
    ),
    # 12 — p102 personal: why I photograph every job
    dict(
        pillar="personal",
        topic="Why I photograph every job",
        slug="boiler-repair", suffix="job-photos",
        hint="brand:wes_with_phone", itype="brand", banner="lower",
        caption="Every job, photographed 📸",
        cta="QUOTE", extra_cta=None,
        fb="📸 Before I start. While it's open. When it's done.\n\nI photograph every job, and it's not for the 'gram. Here's why:\n\n✅ You see exactly what I saw — the worn part, the scale, the sludge. You're never just taking my word for it.\n✅ Landlords get a proper record for their files\n✅ If anything's ever queried later, the answer is in the camera roll, not anyone's memory\n\nTrust is easy to claim and hard to prove. Photos do the proving.",
        ig="Before I start. While it's open. When it's done. 📸\n\nI photograph every single job — and not for the 'gram.\n\n✅ You see exactly what I saw: the worn part, the scale, the sludge\n✅ You're never just taking my word for what needed doing\n✅ Landlords get a proper record for the file\n✅ Any question later — the answer's in the camera roll\n\nTrust is easy to claim. Photos do the proving.",
        tw="I photograph every job — before, during, after. 📸\n\nYou see exactly what I saw. Landlords get records. Questions later? The answer's in the camera roll.\n\nTrust is easy to claim. Photos prove it.",
        gb="Every job I do gets photographed — before I start, while the system is open, and when it's finished. It's a simple habit with real value for customers. You see exactly what I found: the worn part, the scaled heat exchanger, the sludge in the filter — so you're never just taking an engineer's word for what needed doing. Landlords receive a proper photographic record for their files, useful alongside gas safety paperwork. And if any question comes up months later, the answer is in the photos rather than anyone's memory. It's a small thing that keeps everything transparent, on every boiler repair and service across Southampton.",
        tags=["#HonestTrade", "#BoilerRepair", "#Transparency", "#TradesLife"],
    ),
    # 13 — p103 local: Sholing
    dict(
        pillar="local",
        topic="Area coverage — Sholing",
        slug="boiler-service", suffix="sholing",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering Sholing 📍",
        cta="SERVICE", extra_cta=None,
        fb="📍 Sholing — you're on the round.\n\nPlenty of 1930s semis and post-war homes out your way, and plenty of boilers that have quietly missed a few services.\n\n🔥 Annual boiler servicing that actually checks things — flue gases, gas pressure, expansion vessel, filter clean\n🔧 Repairs with a £100 diagnostic\n🚿 Plumbing odd jobs while I'm there\n\nLocal means local: I'm minutes away, not dispatched from a depot.",
        ig="Sholing, you're on the round 📍\n\nPlenty of 1930s semis out your way — and plenty of boilers that have quietly missed a few annual services.\n\n🔥 Proper servicing: flue gases, gas pressure, expansion vessel, filter clean\n🔧 Repairs with a £100 diagnostic\n🚿 Plumbing odd jobs while I'm there\n\nLocal means local. Minutes away, not dispatched from a depot.",
        tw="Sholing 📍 On the round — proper boiler servicing (flue gases, pressures, filter clean), repairs and plumbing. Local means minutes away, not a depot dispatch.",
        gb="Sholing residents — boiler servicing, repairs and plumbing are all covered on my regular round. The area's 1930s semis and post-war homes often have heating systems that have quietly missed a few annual services, and that's where small faults grow into winter breakdowns. My service is a proper inspection: flue gas analysis, gas pressure checks, expansion vessel test and magnetic filter clean, with photos of what I find. Repairs start with a £100 diagnostic that covers most minor fixes on the spot. Being genuinely local means I'm minutes away rather than dispatched from a depot, and you deal with the same person every time.",
        tags=["#Sholing", "#SO19", "#BoilerService", "#LocalTrades"],
    ),
    # 14 — p104 tips: radiator balancing basics
    dict(
        pillar="tips",
        topic="Why one radiator is always cold — balancing basics",
        slug="radiators", suffix="radiator-balancing",
        hint="asset:radiator", itype="asset", banner="upper",
        caption="Why one radiator's always cold 🥶",
        cta=None, extra_cta="Save this for the first cold week of autumn.",
        fb="🥶 One radiator roasting, another barely warm? That's not a broken rad — it's an unbalanced system.\n\nHot water is lazy. It takes the easiest route back to the boiler, so the radiators nearest it hog the flow and the far ones get leftovers.\n\nBalancing fixes it: the lockshield valve (the capped one) gets closed down slightly on the greedy rads, pushing flow out to the lazy ones.\n\n⚠️ If a rad is cold at the BOTTOM though, that's sludge, not balance — different problem, different fix.",
        ig="One radiator roasting, another barely warm? 🥶\n\nThat's not a broken radiator — it's an unbalanced system.\n\nHot water is lazy: it takes the shortest route back to the boiler. The rads nearest it hog the flow, the far ones get leftovers.\n\nThe fix is balancing — closing the lockshield valve (the capped one) slightly on the greedy radiators to push flow to the lazy ones.\n\n⚠️ Cold at the BOTTOM is different — that's sludge, not balance.",
        tw="One rad roasting, another barely warm? That's balance, not a fault. 🥶 Closing the lockshield on greedy rads pushes flow to the lazy ones.\n\nCold at the BOTTOM = sludge. Different fix.",
        gb="If one radiator in your home roasts while another barely warms up, the radiator itself is rarely the problem — the system is out of balance. Heated water naturally takes the easiest route back to the boiler, so radiators closest to it take more than their share of the flow while distant ones receive leftovers. Balancing corrects this: the lockshield valve on each radiator is adjusted so flow is distributed evenly around the house. It's a methodical job with a thermometer rather than guesswork. Note that a radiator cold at the bottom is a different issue — that points to sludge build-up, which balancing won't cure. Radiator work across Southampton.",
        tags=["#RadiatorTips", "#CentralHeating", "#HeatingTips", "#HomeTips"],
    ),
    # 15 — p105 work: tidy pipework pride (manifold)
    dict(
        pillar="work",
        topic="Job story — the pipework nobody will ever see",
        slug="central-heating", suffix="neat-pipework",
        hint="work:manifold", itype="work", banner="lower",
        caption="Pipework you'll never see. Still neat.",
        cta="QUOTE", extra_cta=None,
        fb="🔧 The floorboards went back down over this an hour after the photo.\n\nNobody will ever see it again. So why bother making it neat?\n\nBecause straight, clipped, properly supported pipework doesn't rattle when the heating fires. It doesn't rub through on a joist in year eight. The next engineer can trace every run in seconds instead of guessing.\n\nNeat isn't about looks. Neat is what reliable looks like before the floor goes down.",
        ig="The floorboards went down over this an hour later 🔧\n\nNobody will ever see this pipework again. So why make it neat?\n\nBecause straight, clipped, supported runs don't rattle when the heating fires. They don't rub through on a joist in year eight. And the next person under this floor can trace every pipe in seconds.\n\nNeat isn't about looks. Neat is what reliable looks like before the floor goes down.",
        tw="Floorboards went down over this an hour later. Nobody will ever see it. 🔧\n\nNeat pipework doesn't rattle, doesn't rub through joists, and the next engineer can trace it in seconds. Neat = reliable.",
        gb="This pipework disappeared under floorboards an hour after the photo was taken — and that's exactly why it matters. Straight, clipped, properly supported pipe runs don't rattle when the heating fires up, don't rub through against joists years later, and can be traced in seconds by the next engineer who lifts that floor. Workmanship you'll never see is where reliability is actually built; corners cut under floors become mystery noises and slow leaks long after the installer is gone. Every central heating job I do across Southampton is finished to this standard, whether it's on show or buried — with photos so you see it before it's covered.",
        tags=["#CentralHeating", "#QualityWork", "#Pipework", "#Tradesmanship"],
    ),
    # 16 — p106 cost_reveal: hard water limescale cost in Southampton
    dict(
        pillar="cost_reveal",
        topic="What Southampton's hard water quietly costs your boiler",
        slug="boiler-service", suffix="hard-water",
        hint="ai", itype="ai", banner="lower",
        caption="Hard water is taxing your boiler 💧",
        cta="SERVICE", extra_cta=None,
        fb="💧 Southampton sits on hard water — and your kettle has been trying to tell you for years.\n\nThat same crusty scale forms inside your boiler's heat exchanger. Scale is an insulator: the thicker it gets, the harder the boiler works to push the same heat into your water. You pay for that extra work on every single gas bill.\n\nLeft long enough, it 'kettles' — that rumbling, boiling-pot noise — and parts start failing early.\n\nAn annual service catches scale problems early, and the right water treatment slows the build-up right down.",
        ig="Look inside your kettle. Your boiler looks the same. 💧\n\nSouthampton is a hard-water city — and the scale crusting your kettle is also forming inside your boiler's heat exchanger.\n\nScale insulates. The thicker it gets, the harder the boiler works for the same heat — and you pay the difference on every gas bill.\n\nLeft alone it 'kettles' (that rumbling boiling-pot noise) and parts fail early.\n\nAn annual service + the right water treatment slows it right down.",
        tw="Your kettle's limescale? It's inside your boiler too. 💧\n\nHard water coats the heat exchanger — the boiler works harder, you pay more, parts fail early. A service catches it early.",
        gb="Southampton is a hard-water area, and the limescale you see in your kettle is also forming where you can't see it — inside your boiler's heat exchanger. Scale acts as an insulating layer, so the boiler has to work progressively harder to transfer the same heat into your water, and that extra work shows up on every gas bill. Left unchecked it leads to 'kettling', the rumbling noise of water boiling against scaled metal, and to premature component failure. An annual service identifies scale issues early, and appropriate water treatment — inhibitor and a scale reducer where suitable — slows the build-up considerably. Worth addressing before winter.",
        tags=["#HardWater", "#Limescale", "#BoilerService", "#GasBill"],
        prompt="SCENE: a bright UK kitchen worktop, natural window light, photorealistic close-up.\nSUBJECT: an open stainless kettle showing heavy white limescale crusted on its heating element, a glass of clear water beside it. Text on a clean navy banner across the lower third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Hard water is taxing your boiler 💧\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; cool clean palette, no people, no brand logos.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos. Photorealistic, not illustrative.",
    ),
    # 17 — p107 emergency: frozen condensate quick fix
    dict(
        pillar="emergency",
        topic="Frozen condensate pipe — the quick fix walkthrough",
        slug="boiler-repair", suffix="frozen-condensate-fix",
        hint="ai", itype="ai", banner="upper",
        caption="Frozen condensate? Try this first ❄️",
        cta=None, extra_cta="Save this for the first hard frost.",
        fb="❄️ First hard frost of winter, boiler's dead, and there's a gurgling noise? Nine times out of ten it's a frozen condensate pipe — and you can often fix it yourself in ten minutes.\n\n1️⃣ Find the white plastic pipe running from the boiler to an outside drain\n2️⃣ Pour WARM water along it — never boiling, it can crack the pipe\n3️⃣ A hot water bottle held on the frozen section works too\n4️⃣ Once thawed, reset the boiler\n\nIf it fires up — sorted. If it locks out again, there's more going on and it needs a proper look.",
        ig="The 10-minute fix for a frosty-morning boiler death ❄️\n\nFirst hard frost, no heating, gurgling noise from the boiler? It's almost always a frozen condensate pipe.\n\n1️⃣ Find the white plastic pipe running outside from the boiler\n2️⃣ Pour WARM water along it — never boiling (it can crack the pipe)\n3️⃣ Hot water bottle on the frozen bit works too\n4️⃣ Reset the boiler once thawed\n\nFires up? Sorted. Locks out again? Something more is going on — get it looked at.",
        tw="Boiler dead on a frosty morning + gurgling = frozen condensate pipe ❄️\n\nPour WARM (never boiling) water along the white outside pipe, then reset. Locks out again? Get it looked at.",
        gb="On the first hard frost of winter, one fault accounts for a huge share of 'dead boiler' calls: the frozen condensate pipe. It's the white plastic pipe that runs from your boiler to an outside drain, and when the trapped water inside freezes, the boiler shuts itself down — often with a gurgling sound and a fault code. The fix is frequently something you can do yourself: pour warm (never boiling) water along the frozen section, or hold a hot water bottle against it, then reset the boiler. If it fires up, you're sorted; if it locks out again, there's an underlying issue worth a professional look. Boiler repairs across Southampton.",
        tags=["#BoilerTips", "#WinterTips", "#FrozenPipe", "#BoilerRepair"],
        prompt="SCENE: a UK house exterior brick wall on a frosty winter morning, low golden light, visible frost on surfaces, photorealistic.\nSUBJECT: a white plastic condensate pipe running down the brick wall to a drain, a jug of warm water being poured along the frosted pipe by a gloved hand entering frame from the side. Text on a clean navy banner across the upper third reads (EXACT TEXT, verbatim, no substitutions, no duplicates): \"Frozen condensate? Try this first ❄️\"\nDETAILS: navy #0A2540 banner with a thin orange #FF6B00 accent bar, white bold sans-serif type; cold blue-and-brick palette, gentle steam rising from the warm water.\nUSE CASE: Instagram social post, square 1:1, 1080x1080.\nCONSTRAINTS: Render text verbatim, no extra words, no duplicate lines, no fake logos. Photorealistic, not illustrative. Only one hand and jug visible, no face, no extra pipes or fittings.",
    ),
    # 18 — p108 personal: first boiler install memory
    dict(
        pillar="personal",
        topic="My first solo boiler install",
        slug="boiler-install", suffix="first-install",
        hint="brand:wes_with_tools", itype="brand", banner="lower",
        caption="My first install. Still proud. 🔧",
        cta="QUOTE", extra_cta=None,
        fb="🔧 I still remember my first solo boiler install.\n\nA straightforward combi swap that should've taken a day. I took a day and a half — because I checked every joint, every reading, every setting about five times. The customer kept the tea coming and politely didn't ask why I kept staring at the flue analyser.\n\nThat boiler's still running today.\n\nThe speed came with the years. The five-times checking never left — it just got faster. Some habits you keep on purpose.",
        ig="My first solo boiler install 🔧\n\nA simple combi swap. Should've taken a day — took me a day and a half, because I checked every joint, every reading, every setting five times over.\n\nThe customer kept the tea coming and politely didn't ask why I kept staring at the flue analyser. 😄\n\nThat boiler is still running today.\n\nThe speed came with experience. The five-times checking never left — it just got quicker. Some habits you keep on purpose.",
        tw="My first solo boiler install took a day and a half instead of a day — I checked everything five times. 🔧\n\nIt's still running today.\n\nThe speed came with the years. The checking never left.",
        gb="Every engineer remembers their first solo installation. Mine was a straightforward combi swap that should have taken a day — and took a day and a half, because I checked every joint, every gas reading and every setting about five times over. The customer kept the tea coming and was kind enough not to ask why I kept re-running the flue analysis. That boiler is still running today. Years on, the speed has come, but the habit of double-checking never left — it just got faster. It's the same care that goes into every boiler installation I do across Southampton now, from survey to handover.",
        tags=["#BoilerInstall", "#NewBoiler", "#TradesLife", "#HeatingEngineerLife"],
    ),
    # 19 — p109 local: Netley
    dict(
        pillar="local",
        topic="Area coverage — Netley",
        slug="plumbing", suffix="netley",
        hint="asset:van_southampton", itype="asset", banner="lower",
        caption="Covering Netley 📍",
        cta="QUOTE", extra_cta=None,
        fb="📍 Netley — yes, I come out your way.\n\nBetween the abbey ruins and the shore, there's a lot of older housing stock with character… and character means quirky plumbing. Victorian cottages with mystery pipe runs, extensions joined onto extensions, stopcocks in places that make no sense.\n\n🚿 Plumbing repairs, taps, toilets and leaks\n🔧 Boiler repairs and servicing\n🚐 Same one-man service as everywhere else on the round\n\nQuirky pipes don't scare me. They're half the fun.",
        ig="Netley, you're covered 📍\n\nBetween the abbey and the shore there's a lot of lovely older housing — and older housing means quirky plumbing. Victorian cottages with mystery pipe runs, extensions on extensions, stopcocks hiding in odd corners.\n\n🚿 Plumbing repairs, taps, toilets, leaks\n🔧 Boiler repairs and servicing too\n\nQuirky pipes don't scare me. They're half the fun.",
        tw="Netley 📍 Covered — plumbing repairs, taps, toilets, leaks, plus boilers. Older cottages with mystery pipework are half the fun of the job.",
        gb="Netley is firmly on my round. The village's older housing stock — Victorian cottages, converted buildings and homes extended over decades — tends to come with plumbing quirks: mystery pipe runs, stopcocks in unexpected places, and fittings from several different eras joined together. That's familiar territory. I handle plumbing repairs, tap and toilet faults, and leak tracing, alongside boiler repairs and servicing, all with clear pricing agreed before work starts. As a sole trader, the person you message is the person who turns up — and who knows the area's housing rather than learning it on your time. Covering Netley, Hamble-side and the wider Southampton area.",
        tags=["#Netley", "#SO31", "#PlumbingRepairs", "#LocalTrades"],
    ),
    # 20 — p110 cost_reveal: the 1-degree thermostat rule
    dict(
        pillar="cost_reveal",
        topic="The one-degree thermostat rule — what it saves",
        slug="heating-controls", suffix="one-degree",
        hint="asset:smart", itype="asset", banner="upper",
        caption="Turn it down one degree 🌡️",
        cta=None, extra_cta="Save this one — it's the easiest money you'll keep this year.",
        fb="🌡️ The cheapest heating upgrade in Britain costs nothing: one degree.\n\nDropping the thermostat from 21°C to 20°C is barely noticeable on your skin — but it can shave up to 10% off heating use over a year. On a typical bill, that's serious money for zero effort.\n\nMake it painless:\n✅ Drop it one degree, live with it a week\n✅ Wear the jumper your nan knitted you\n✅ Pair it with TRVs so unused rooms aren't heated to lounge temperature\n\nIf your thermostat can't do schedules, that's fixable too.",
        ig="The cheapest heating upgrade in Britain: one degree 🌡️\n\n21°C → 20°C is barely noticeable on your skin — but it can cut heating use by up to 10% over a year. Real money, zero effort.\n\nMake it painless:\n✅ Drop one degree, live with it for a week\n✅ Jumpers exist — wear the good one\n✅ Pair with TRVs so empty rooms aren't heated like the lounge\n\nIf your thermostat can't even do schedules, that's a fixable problem too.",
        tw="The cheapest heating upgrade in Britain: turn the thermostat down 1°C. 🌡️\n\nBarely noticeable on your skin — up to 10% off heating use over a year. Zero cost, zero effort.",
        gb="The simplest saving in home heating costs nothing at all: lowering your thermostat by one degree. The difference between 21°C and 20°C is barely perceptible day to day, yet it can reduce annual heating use by as much as ten percent — a meaningful sum on any household's bill. To make it painless, drop one degree and live with it for a week before judging, and pair the change with thermostatic radiator valves so unused rooms aren't heated to living-room temperatures. If your current thermostat can't run a proper schedule, upgrading your heating controls multiplies the saving further. Heating controls fitted and configured across Southampton.",
        tags=["#EnergySaving", "#HeatingControls", "#ThermostatTips", "#EnergyBills"],
    ),
]
